import{Pool}from'pg';
const url=process.env.DOMAIN11J_DATABASE_URL;if(process.env.DOMAIN11J_CERTIFICATION_MODE==='true'&&!url)throw new Error('DOMAIN11J_DATABASE_URL required in certification mode');const d=url?describe:describe.skip;
d('11J V2 PostgreSQL hardening',()=>{const p=new Pool({connectionString:url});afterAll(async()=>p.end());
 test('worker has exact coordination privileges',async()=>{const q=await p.query(`select has_table_privilege('tcds_governance_control_worker_runtime','arb.control_rule_trigger_receipts_11j','SELECT,INSERT') a,has_table_privilege('tcds_governance_control_worker_runtime','arb.control_action_ack_receipts_11j','SELECT') b,has_table_privilege('tcds_governance_control_worker_runtime','arb.control_manual_approvals_11j','SELECT') c`);expect(q.rows[0]).toEqual({a:true,b:true,c:true})});
 test('admin cannot approve recovery',async()=>{const q=await p.query(`select has_function_privilege('tcds_governance_control_admin','arb.domain11j_approve_recovery_user_v2(uuid,uuid,text,text,uuid,uuid)','EXECUTE') x`);expect(q.rows[0].x).toBe(false)});
 test('approval role cannot evaluate',async()=>{const q=await p.query(`select has_function_privilege('tcds_governance_control_recovery_approver','arb.domain11j_evaluate_rule(text,text,uuid,uuid,uuid,uuid,text)','EXECUTE') x`);expect(q.rows[0].x).toBe(false)});
 test('failed actions cannot be marked effective',async()=>{const q=await p.query(`select count(*)::int n from arb.v_domain11j_effective_controls_v2 where enforcement_status='FAILED' and enforcement_effective`);expect(q.rows[0].n).toBe(0)});
 test('active policy rule set is exact',async()=>{const q=await p.query(`with p as(select c.configuration_document cfg from arb.v_effective_policy_versions v join arb.policy_version_configurations c using(governance_policy_version_id) where v.policy_code='AUTOMATED_SAFETY_CONTROL_POLICY' limit 1),pc as(select x->>'ruleCode' code from p,jsonb_array_elements(cfg->'controlRules') x),ac as(select rule_code code from arb.control_rule_active_11j) select count(*)::int n from((select code from pc except select code from ac) union all (select code from ac except select code from pc))x`);expect(q.rows[0].n).toBe(0)});
});
