import { Link, useNavigate } from 'react-router-dom';
import { AlertTriangle, ArrowRight, PackageCheck, RefreshCw, RotateCcw, ScanLine, Truck } from 'lucide-react';
import { AppHeader } from '../components/AppHeader';
import { ScreenCard } from '../components/ScreenCard';
import { appRoutes } from '../config/routes';
import { useDashboard } from '../features/dashboard/hooks/useDashboard';

const icons = { RECEIVING: ScanLine, PICKING: PackageCheck, SHIPPING: Truck, RETURNS: RotateCcw, EXCEPTIONS: AlertTriangle } as const;
export function Dashboard() {
  const { data, loading, error, refresh } = useDashboard(); const navigate = useNavigate();
  if (error === 'SESSION_EXPIRED') navigate('/', { replace: true });
  return <><AppHeader title="Dashboard" subtitle="Today’s warehouse command center" />
    <div className="mx-auto max-w-md space-y-5 p-4 pb-28">
      <div className="px-1"><p className="font-display text-card font-black text-tcds-ink">Good morning, {data?.operator.displayName ?? 'Warehouse Operator'}</p><p className="mt-1 text-body font-medium text-tcds-muted">{data ? `${data.facility.facilityName} · ${data.station.stationName}` : 'Loading facility and station context…'}</p></div>
      {error && data && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-900">Live refresh failed. Showing the last verified dashboard snapshot.</div>}
      <ScreenCard className="overflow-hidden p-0">
        <div className="relative overflow-hidden bg-tcds-black p-6 text-white"><div className="absolute -right-10 -top-12 h-44 w-44 bg-[url('/tcds-logo.svg')] bg-contain bg-no-repeat opacity-[.07]"/><p className="relative text-caption font-black uppercase tracking-[0.30em] text-tcds-gold">Live Queue</p><div className="relative flex items-start justify-between gap-3"><div><h2 className="mt-2 font-display text-display font-black">Today&apos;s Operations</h2><p className="mt-2 text-body text-white/65">Prioritized work, blocked items, and urgent activity.</p></div><button onClick={() => void refresh()} className="tcds-focus rounded-xl border border-white/15 p-2" aria-label="Refresh dashboard"><RefreshCw size={18}/></button></div></div>
        <div className="space-y-3 p-4">{loading && !data ? [1,2,3,4,5].map(i => <div key={i} className="skeleton h-28 rounded-enterprise"/>) : data?.queues.map(q => { const Icon = icons[q.key]; return <Link key={q.key} to={q.route} className="enterprise-motion block rounded-enterprise border border-tcds-line bg-white p-4 shadow-surface hover:border-tcds-gold/40 hover:shadow-card"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-enterprise bg-tcds-surface text-tcds-gold"><Icon size={21}/></div><div><p className="font-display text-card font-black text-tcds-ink">{q.label}</p><p className="mt-0.5 text-caption font-semibold text-tcds-muted">{q.description}</p><p className="mt-2 text-caption font-semibold text-neutral-500">Blocked {q.blockedCount} · High priority {q.highPriorityCount}</p></div></div><p className="font-display text-page font-black text-tcds-gold">{q.count}</p></div><div className="mt-3 flex items-center justify-between border-t border-tcds-line pt-3 text-caption font-black text-tcds-ink"><span>{q.actionLabel}</span><ArrowRight size={16} className="text-tcds-gold"/></div></Link>; })}</div>
      </ScreenCard>
      <ScreenCard><div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-caption font-black uppercase tracking-[0.24em] text-tcds-gold">Infrastructure</p><h2 className="mt-1 font-display text-section font-black text-tcds-ink">System Status</h2></div><span className={`rounded-full px-3 py-1 text-caption font-black ${data?.station.ready ? 'bg-emerald-50 text-tcds-green':'bg-amber-50 text-amber-800'}`}>{data?.station.ready ? 'Station ready':'Attention required'}</span></div><div className="grid grid-cols-2 gap-2">{data?.health.map(h => <div key={h.key} className="rounded-enterprise border border-tcds-line bg-tcds-surface p-3"><p className="font-display text-caption font-black text-tcds-ink">{h.label}</p><p className={`mt-1 text-caption font-semibold ${h.state==='HEALTHY'?'text-tcds-green':h.state==='CRITICAL'?'text-tcds-red':'text-tcds-warning'}`}>{h.detail}</p></div>) ?? <div className="skeleton col-span-2 h-24 rounded-enterprise"/>}</div></ScreenCard>
      <ScreenCard><h2 className="font-display text-section font-black text-tcds-ink">Active Operational Alerts</h2><div className="mt-3 space-y-2">{data?.alerts.length ? data.alerts.slice(0,5).map(a => <div key={a.alertId} className="rounded-2xl border border-tcds-line bg-tcds-surface p-3"><p className="font-black text-tcds-ink">{a.title}</p><p className="mt-1 text-sm text-tcds-muted">{a.description}</p></div>) : <p className="text-sm font-semibold text-tcds-muted">No active operational alerts.</p>}</div></ScreenCard>
      <ScreenCard><h2 className="font-display text-section font-black text-tcds-ink">Today’s Activity</h2><div className="mt-3 grid grid-cols-2 gap-3">{data?.metrics.map(m => <div key={m.key} className="rounded-enterprise bg-tcds-surface p-4"><p className="text-caption font-bold text-tcds-muted">{m.label}</p><p className="mt-1 font-display text-page font-black text-tcds-ink">{m.value}</p><p className="mt-1 text-caption text-tcds-muted">{m.detail}</p></div>) ?? [1,2,3,4].map(i=><div key={i} className="skeleton h-24 rounded-enterprise"/>)}</div></ScreenCard>
      <ScreenCard><h2 className="mb-3 font-display text-section font-black text-tcds-ink">Quick Actions</h2><div className="grid grid-cols-2 gap-3">{appRoutes.filter(r => ['/receive','/inventory','/pick','/pack-ship','/returns','/settings'].includes(r.path)).map(({ path,label,icon:Icon }) => <Link key={path} to={path} className="enterprise-motion flex min-h-14 items-center gap-3 rounded-enterprise border border-tcds-line bg-tcds-surface p-4 font-display text-caption font-black text-tcds-ink hover:border-tcds-gold/40"><Icon className="text-tcds-gold" size={20}/>{label}</Link>)}</div></ScreenCard>
    </div></>;
}
