import type { PackShipMessage } from '../types/packShipMessages';

type CatalogEntry = Omit<PackShipMessage, 'code' | 'supportReference'>;

const CATALOG: Record<string, CatalogEntry> = {
  PACK_WRONG_SERIALIZED_ITEM: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'This is not the reserved item', explanation:'The scanned TCDS barcode does not match the exact serialized unit assigned to this order.', nextAction:'Return the item to the tote and scan the expected TCDS barcode.', primaryActionLabel:'Scan Expected Item', secondaryActionLabel:'Report Discrepancy', field:'scan', stage:'CONTENTS' },
  PACK_MISSING_ITEM: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'One required item has not been verified', explanation:'The packing task still has an expected item that has not been scanned and confirmed.', nextAction:'Review the tote contents or report the item missing.', primaryActionLabel:'Review Contents', secondaryActionLabel:'Report Missing Item', stage:'CONTENTS' },
  PACK_EXTRA_ITEM: { severity:'ERROR', presentation:'SHEET', blocking:true, retryable:false, title:'An unexpected item was scanned', explanation:'This item is not assigned to the packing task and must not be included in the package.', nextAction:'Remove the item and start a discrepancy review.', primaryActionLabel:'Start Review', secondaryActionLabel:'Contact Supervisor', stage:'CONTENTS' },
  PACK_DUPLICATE_SCAN: { severity:'WARNING', presentation:'INLINE', blocking:false, retryable:true, title:'This item was already confirmed', explanation:'The barcode belongs to an item already verified for this package.', nextAction:'Continue with the next expected item.', field:'scan', stage:'CONTENTS' },
  PACK_ORDER_CANCELLED: { severity:'CRITICAL', presentation:'SHEET', blocking:true, retryable:false, title:'Packing stopped because the order was cancelled', explanation:'The order is no longer authorized for shipment.', nextAction:'Do not ship. Follow the return-to-inventory instructions.', primaryActionLabel:'View Return Instructions', secondaryActionLabel:'Contact Supervisor', stage:'CONTENTS' },
  PACK_RECOMMENDED_BOX_UNAVAILABLE: { severity:'WARNING', presentation:'SHEET', blocking:true, retryable:true, title:'Recommended packaging is unavailable', explanation:'The approved packaging profile cannot be completed with the selected carton.', nextAction:'Select an approved alternative and provide a reason.', primaryActionLabel:'Choose Alternative', secondaryActionLabel:'Request Manager Review', stage:'PACKAGING' },
  PACK_ITEM_DOES_NOT_FIT: { severity:'ERROR', presentation:'INLINE', blocking:true, retryable:true, title:'Package dimensions are incompatible with the item', explanation:'The selected package cannot safely contain the item and required protection.', nextAction:'Choose a larger approved package.', stage:'PACKAGING' },
  PACK_DIMENSIONAL_WEIGHT_SPIKE: { severity:'WARNING', presentation:'BANNER', blocking:true, retryable:true, title:'This carton significantly increases shipping cost', explanation:'The selected dimensions produce a material dimensional-weight increase.', nextAction:'Repack the item or request approval.', primaryActionLabel:'Repack', secondaryActionLabel:'Request Approval', stage:'PACKAGING' },
  PACK_HAZARD_CONFLICT: { severity:'CRITICAL', presentation:'SHEET', blocking:true, retryable:false, title:'Packaging is not approved for this item', explanation:'The carton or materials conflict with the item battery or hazard profile.', nextAction:'Stop packing and request supervisor review.', primaryActionLabel:'Request Supervisor Review', stage:'PACKAGING' },
  PACK_SCALE_OFFLINE: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Scale is not connected', explanation:'The Device Gateway is not receiving data from the approved scale.', nextAction:'Check the Gateway, scale power, and USB connection.', primaryActionLabel:'Retry Scale', secondaryActionLabel:'Request Approved Fallback', field:'weight', stage:'MEASUREMENTS' },
  PACK_SCALE_UNSTABLE: { severity:'WARNING', presentation:'INLINE', blocking:true, retryable:true, title:'Weight is still changing', explanation:'The package weight has not stabilized.', nextAction:'Center the package, remove your hands, and wait for a stable reading.', primaryActionLabel:'Try Again', field:'weight', stage:'MEASUREMENTS' },
  PACK_LENGTH_INVALID: { severity:'ERROR', presentation:'INLINE', blocking:true, retryable:true, title:'Length must be greater than zero', explanation:'A valid sealed-package length is required.', nextAction:'Measure the longest side of the sealed package.', field:'length', stage:'MEASUREMENTS' },
  PACK_WIDTH_INVALID: { severity:'ERROR', presentation:'INLINE', blocking:true, retryable:true, title:'Width must be greater than zero', explanation:'A valid sealed-package width is required.', nextAction:'Measure the second-longest side of the sealed package.', field:'width', stage:'MEASUREMENTS' },
  PACK_HEIGHT_INVALID: { severity:'ERROR', presentation:'INLINE', blocking:true, retryable:true, title:'Height must be greater than zero', explanation:'A valid sealed-package height is required.', nextAction:'Measure the remaining side of the sealed package.', field:'height', stage:'MEASUREMENTS' },
  PACK_SCANNER_OFFLINE: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Scanner is unavailable', explanation:'The approved scanner is not connected to this station.', nextAction:'Reconnect the scanner or request the approved manual-entry fallback.', primaryActionLabel:'Retry Scanner', secondaryActionLabel:'Request Fallback', stage:'CONTENTS' },
  PACK_PRINTER_OFFLINE: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Zebra printer is unavailable', explanation:'The Device Gateway cannot reach the configured label printer.', nextAction:'Check printer power, network, labels, and Gateway status.', primaryActionLabel:'Retry Printer', secondaryActionLabel:'Open Hardware Help', stage:'LABEL' },
  PACK_WRONG_LABEL_STOCK: { severity:'ERROR', presentation:'SHEET', blocking:true, retryable:true, title:'Wrong label stock is loaded', explanation:'The printer is not loaded with the approved 4×6 carrier-label stock.', nextAction:'Load approved stock, then retry the existing print job.', primaryActionLabel:'Retry Existing Print', stage:'LABEL' },
  PACK_PARTIAL_PRINT: { severity:'ERROR', presentation:'SHEET', blocking:true, retryable:true, title:'The carrier label did not print completely', explanation:'The existing label purchase is valid, but the physical print is incomplete or unreadable.', nextAction:'Reprint the same label. Do not purchase another label.', primaryActionLabel:'Reprint Existing Label', secondaryActionLabel:'Contact Supervisor', stage:'LABEL' },
  SHIP_ADDRESS_CORRECTED: { severity:'WARNING', presentation:'SHEET', blocking:true, retryable:true, title:'The carrier recommends a standardized address', explanation:'The destination differs from the carrier-normalized format.', nextAction:'Compare both addresses and accept the correction or request review.', primaryActionLabel:'Review Address', secondaryActionLabel:'Request Manager Review', field:'address', stage:'ADDRESS' },
  SHIP_ADDRESS_AMBIGUOUS: { severity:'ERROR', presentation:'SHEET', blocking:true, retryable:true, title:'Multiple valid destinations were found', explanation:'The address cannot be resolved to one delivery point without confirmation.', nextAction:'Select the verified destination or request customer/manager review.', primaryActionLabel:'Review Destinations', secondaryActionLabel:'Request Review', field:'address', stage:'ADDRESS' },
  SHIP_ADDRESS_UNDELIVERABLE: { severity:'CRITICAL', presentation:'BANNER', blocking:true, retryable:false, title:'No approved carrier can deliver to this address', explanation:'The destination failed authoritative address and service validation.', nextAction:'Stop shipping and escalate for address correction.', primaryActionLabel:'Request Address Review', field:'address', stage:'ADDRESS' },
  SHIP_CARRIER_API_UNAVAILABLE: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Carrier rates are temporarily unavailable', explanation:'The shipping service could not retrieve current carrier options.', nextAction:'Retry later. Packing evidence remains saved.', primaryActionLabel:'Retry Rates', secondaryActionLabel:'Contact Supervisor', field:'rate', stage:'RATES' },
  SHIP_RATE_EXPIRED: { severity:'WARNING', presentation:'INLINE', blocking:true, retryable:true, title:'This shipping rate has expired', explanation:'Carrier pricing or service availability changed after the quote was returned.', nextAction:'Refresh rates and select an approved current option.', primaryActionLabel:'Refresh Rates', field:'rate', stage:'RATES' },
  SHIP_INSURANCE_UNAVAILABLE: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Required coverage is not available', explanation:'The selected carrier service cannot provide the insurance required for this shipment value.', nextAction:'Select another approved carrier or service.', primaryActionLabel:'Choose Another Service', stage:'RATES' },
  SHIP_SIGNATURE_INCOMPATIBLE: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Required signature service is unavailable', explanation:'The selected service does not support the required signature or restricted-delivery level.', nextAction:'Select another approved service.', primaryActionLabel:'Choose Another Service', stage:'RATES' },
  SHIP_LABEL_PURCHASE_UNCERTAIN: { severity:'CRITICAL', presentation:'SHEET', blocking:true, retryable:true, title:'The carrier label may already exist', explanation:'The carrier may have created the label, but the response was interrupted.', nextAction:'Do not purchase another label. Check the existing shipment status first.', primaryActionLabel:'Check Label Status', secondaryActionLabel:'Contact Supervisor', field:'label', stage:'LABEL', steps:['Check the existing shipment status.','Search using the current idempotency reference.','Retry only after the server confirms that no label exists.'] },
  SHIP_DUPLICATE_LABEL_BLOCKED: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:false, title:'A label has already been purchased', explanation:'Duplicate carrier charges were blocked for this package.', nextAction:'Use the existing label and print job.', primaryActionLabel:'View Existing Label', field:'label', stage:'LABEL' },
  SHIP_TRACKING_MISMATCH: { severity:'CRITICAL', presentation:'SHEET', blocking:true, retryable:true, title:'The scanned carrier label does not belong to this package', explanation:'The carrier tracking barcode is linked to a different package or shipment.', nextAction:'Remove the label and start an investigation.', primaryActionLabel:'Start Investigation', secondaryActionLabel:'Contact Supervisor', field:'tracking', stage:'LABEL' },
  SHIP_LABEL_UNREADABLE: { severity:'ERROR', presentation:'INLINE', blocking:true, retryable:true, title:'The tracking barcode could not be verified', explanation:'The scanner cannot read the applied carrier label.', nextAction:'Reprint the same label and verify it again.', primaryActionLabel:'Reprint Same Label', field:'tracking', stage:'LABEL' },
  SHIP_LABEL_VOIDED: { severity:'CRITICAL', presentation:'BANNER', blocking:true, retryable:false, title:'This carrier label is no longer valid', explanation:'The carrier or TCDS voided the label after it was issued.', nextAction:'Remove it and request a replacement through the system.', primaryActionLabel:'Request Replacement', stage:'LABEL' },
  PACK_EVIDENCE_MISSING: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Required packing evidence is incomplete', explanation:'One or more required artifacts have not been accepted and committed.', nextAction:'Capture the listed artifacts before continuing.', primaryActionLabel:'Capture Evidence', stage:'EVIDENCE' },
  PACK_EVIDENCE_PENDING: { severity:'INFO', presentation:'BANNER', blocking:true, retryable:true, title:'Evidence verification is still processing', explanation:'Uploaded artifacts are awaiting quality or integrity assessment.', nextAction:'Wait or continue with nonblocking work.', primaryActionLabel:'Refresh Status', stage:'EVIDENCE' },
  PACK_EVIDENCE_HASH_MISMATCH: { severity:'CRITICAL', presentation:'SHEET', blocking:true, retryable:false, title:'Evidence integrity verification failed', explanation:'The stored artifact does not match its expected cryptographic hash.', nextAction:'Stop. Do not ship. Request security review.', primaryActionLabel:'Request Security Review', stage:'EVIDENCE' },
  PACK_PACKAGE_REOPENED: { severity:'CRITICAL', presentation:'SHEET', blocking:true, retryable:true, title:'The sealed package appears to have been reopened', explanation:'The package seal or evidence state changed after completion.', nextAction:'Restart final evidence and sealing checks.', primaryActionLabel:'Restart Final Checks', stage:'EVIDENCE' },
  PACK_FINAL_WEIGHT_CHANGED: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'Final weight differs from the approved packed weight', explanation:'The sealed package weight changed beyond the permitted tolerance.', nextAction:'Reopen packing review and verify the contents.', primaryActionLabel:'Reopen Packing Review', stage:'MEASUREMENTS' },
  SESSION_EXPIRED: { severity:'ERROR', presentation:'SHEET', blocking:true, retryable:false, title:'Your secure session expired', explanation:'The task remains protected, but new actions require authentication.', nextAction:'Sign in again, then resume the packing task.', primaryActionLabel:'Sign In Again' },
  NETWORK_ERROR: { severity:'ERROR', presentation:'BANNER', blocking:true, retryable:true, title:'The warehouse service could not be reached', explanation:'Your last action was not confirmed by the server.', nextAction:'Check connectivity and retry using the same task. Do not repeat a label purchase until status is confirmed.', primaryActionLabel:'Retry Connection' },
  REQUEST_TIMEOUT: { severity:'WARNING', presentation:'SHEET', blocking:true, retryable:true, title:'The request took too long', explanation:'The server may still be processing the action.', nextAction:'Check the task status before repeating any financial or carrier action.', primaryActionLabel:'Check Current Status', secondaryActionLabel:'Contact Supervisor' },
  UNKNOWN_ERROR: { severity:'ERROR', presentation:'SHEET', blocking:true, retryable:true, title:'The action could not be completed', explanation:'The warehouse system returned an unrecognized operational error.', nextAction:'Retry once. If it continues, contact a supervisor and provide the support reference.', primaryActionLabel:'Retry', secondaryActionLabel:'Contact Supervisor' },
};

export function resolvePackShipMessage(code: string, supportReference?: string, backendMessage?: Partial<PackShipMessage>): PackShipMessage {
  const base = CATALOG[code] || CATALOG.UNKNOWN_ERROR;
  return {
    code,
    ...base,
    ...backendMessage,
    supportReference,
    announce: backendMessage?.announce || `${backendMessage?.title || base.title}. ${backendMessage?.nextAction || base.nextAction}`,
  };
}
