import{ForensicApiError}from'../errors/ForensicApiError';import type{ForensicRequestContext,ForensicLogger}from'../models/orchestrationTypes';import{ForensicOrchestrationRepository}from'../repositories/forensicOrchestrationRepository';import{ArbProcessRepository}from'../repositories/arbProcessRepository';
export class ForensicChainService{constructor(private readonly repo:ForensicOrchestrationRepository,private readonly processes:ArbProcessRepository,private readonly logger:ForensicLogger){}
 private require(ctx:ForensicRequestContext,p:string){if(!ctx.principal.permissions.has(p))throw new ForensicApiError(403,'FORBIDDEN','Insufficient forensic permission');}
 async create(ctx:ForensicRequestContext,input:{chainType:string;policyVersionId?:string;retentionPolicyId?:string;metadata:Record<string,unknown>;idempotencyKey:string}){this.require(ctx,'forensic.chain.create');const run=await this.processes.start('D7_CHAIN_ORCHESTRATE','CREATE','FORENSIC_CHAIN',input.idempotencyKey,ctx.principal.actorType,ctx.principal.actorId,ctx.principal.actorName,ctx.correlationId);try{const c=await this.repo.createChain({...input,tenantKey:ctx.principal.tenantKey,actorType:ctx.principal.actorType,actorId:ctx.principal.actorId,actorName:ctx.principal.actorName,processRunId:run,correlationId:ctx.correlationId});await this.processes.finish(run,'SUCCEEDED',{chainId:c.chain_id});return c;}catch(e){await this.processes.finish(run,'FAILED',{},e instanceof Error?e.message:String(e));throw e;}}
 async get(ctx:ForensicRequestContext,chainId:string){this.require(ctx,'forensic.chain.read');const c=await this.repo.getChain(chainId,ctx.principal.tenantKey);if(!c)throw new ForensicApiError(404,'CHAIN_NOT_FOUND','Forensic chain not found');return c;}
 async timeline(ctx:ForensicRequestContext,chainId:string){await this.get(ctx,chainId);return this.repo.timeline(chainId,ctx.principal.tenantKey);}
 async assess(ctx:ForensicRequestContext,chainId:string,stageCode:string){this.require(ctx,'forensic.stage.assess');const run=await this.processes.start('D7_STAGE_ASSESS',stageCode,'FORENSIC_CHAIN',chainId,ctx.principal.actorType,ctx.principal.actorId,ctx.principal.actorName,ctx.correlationId);try{const a=await this.repo.assess({chainId,tenantKey:ctx.principal.tenantKey,stageCode,actorId:ctx.principal.actorId,processRunId:run});if(!a)throw new ForensicApiError(404,'CHAIN_NOT_FOUND','Forensic chain not found');await this.processes.finish(run,'SUCCEEDED',{assessmentId:a.stage_assessment_id});return a;}catch(e){await this.processes.finish(run,'FAILED',{},e instanceof Error?e.message:String(e));throw e;}}
 async transition(ctx:ForensicRequestContext,chainId:string,input:{toStage:string;idempotencyKey:string}){this.require(ctx,'forensic.chain.transition');const run=await this.processes.start('D7_CHAIN_TRANSITION',input.toStage,'FORENSIC_CHAIN',chainId,ctx.principal.actorType,ctx.principal.actorId,ctx.principal.actorName,ctx.correlationId);try{const t=await this.repo.transition({chainId,tenantKey:ctx.principal.tenantKey,toStage:input.toStage,actorType:ctx.principal.actorType,actorId:ctx.principal.actorId,actorName:ctx.principal.actorName,idempotencyKey:input.idempotencyKey,processRunId:run,correlationId:ctx.correlationId});const blocked=t.request_status==='BLOCKED';await this.processes.finish(run,blocked?'PARTIAL':'SUCCEEDED',{transitionRequestId:t.stage_transition_request_id,blocked});if(blocked)throw new ForensicApiError(409,'TRANSITION_BLOCKED','Forensic transition blocked',t.blocked_reasons_json);return t;}catch(e){if(!(e instanceof ForensicApiError&&e.code==='TRANSITION_BLOCKED'))await this.processes.finish(run,'FAILED',{},e instanceof Error?e.message:String(e));throw e;}}
 async requestManifest(ctx:ForensicRequestContext,chainId:string,input:{manifestType:string;idempotencyKey:string}){this.require(ctx,'forensic.manifest.request');const run=await this.processes.start('D7_MANIFEST_REQUEST',input.manifestType,'FORENSIC_CHAIN',chainId,ctx.principal.actorType,ctx.principal.actorId,ctx.principal.actorName,ctx.correlationId);try{const r=await this.repo.requestManifest({chainId,tenantKey:ctx.principal.tenantKey,manifestType:input.manifestType,actorType:ctx.principal.actorType,actorId:ctx.principal.actorId,idempotencyKey:input.idempotencyKey,processRunId:run,correlationId:ctx.correlationId});await this.processes.finish(run,'SUCCEEDED',{manifestRequestId:r.manifest_request_id,outboxEventId:r.outbox_event_id});return r;}catch(e){await this.processes.finish(run,'FAILED',{},e instanceof Error?e.message:String(e));throw e;}}
}
