module.exports = {
  apps: [
    {
      name: 'arb-api',
      script: './dist/server.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 10000,
      listen_timeout: 10000,
      max_memory_restart: '400M',
      min_uptime: '20s',
      max_restarts: 20,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      out_file: '/srv/arb-system/api/logs/pm2/arb-api-out.log',
      error_file: '/srv/arb-system/api/logs/pm2/arb-api-error.log',
      merge_logs: true,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'comp-analysis-worker',
      script: './dist/workers/compAnalysisWorker.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 15000,
      max_memory_restart: '350M',
      min_uptime: '20s',
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      out_file: '/srv/arb-system/api/logs/pm2/comp-analysis-worker-out.log',
      error_file: '/srv/arb-system/api/logs/pm2/comp-analysis-worker-error.log',
      merge_logs: true,
       env: {
        NODE_ENV: 'production',
        COMP_WORKER_NAME: 'comp-analysis-worker',
        COMP_WORKER_MIN_BUY_OVERALL_SCORE: '0.60',
        COMP_WORKER_MIN_WATCH_OVERALL_SCORE: '0.45',
      },
    },
    {
      name: 'retry-worker',
      script: './dist/workers/retryWorker.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 15000,
      max_memory_restart: '300M',
      min_uptime: '20s',
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      out_file: '/srv/arb-system/api/logs/pm2/retry-worker-out.log',
      error_file: '/srv/arb-system/api/logs/pm2/retry-worker-error.log',
      merge_logs: true,
      env: {
        NODE_ENV: 'production',
        RETRY_WORKER_NAME: 'retry-worker',
      },
    },
    {
      name: 'market-intel-worker',
      script: 'dist/workers/marketIntelWorker.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '350M',
      kill_timeout: 10000,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/srv/arb-system/api/logs/pm2/market-intel-worker.out.log',
      error_file: '/srv/arb-system/api/logs/pm2/market-intel-worker.err.log',
      merge_logs: true,
    },
    {
      name: 'watchlist-worker',
      script: 'dist/workers/watchlistWorker.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      kill_timeout: 10000,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/srv/arb-system/api/logs/pm2/watchlist-worker.out.log',
      error_file: '/srv/arb-system/api/logs/pm2/watchlist-worker.err.log',
      merge_logs: true,
    },
    {
      name: 'opportunity-queue-worker',
      script: 'dist/workers/opportunityQueueWorker.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      kill_timeout: 10000,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/srv/arb-system/api/logs/pm2/opportunity-queue-worker.out.log',
      error_file: '/srv/arb-system/api/logs/pm2/opportunity-queue-worker.err.log',
      merge_logs: true,
    },
   {
  name: 'profit-analysis-worker',
  script: 'dist/workers/profitAnalysisWorker.js',
  instances: 1,
  exec_mode: 'fork',
  autorestart: true,
  watch: false,
  max_memory_restart: '512M',
  env: {
    NODE_ENV: 'production',
    PROFIT_ANALYSIS_BATCH_LIMIT: '50',
    PROFIT_ANALYSIS_POLL_INTERVAL_MS: '30000',
    PROFIT_MIN_ACCEPTED_COMPS: '3',
    PROFIT_BUY_MIN_NET_PROFIT: '20',
    PROFIT_BUY_MIN_MARGIN: '0.22',
    PROFIT_BUY_MIN_ROI: '0.35',
    PROFIT_BUY_MIN_CONFIDENCE: '0.70',
    PROFIT_REVIEW_MIN_NET_PROFIT: '10',
    PROFIT_PAYMENT_FEE_RATE: '0.029',
    PROFIT_PAYMENT_FIXED_USD: '0.30',
    PROFIT_PACKAGING_COST_USD: '2.00',
    PROFIT_RULESET_VERSION: 'profit-rules.v1.0.0',
    PROFIT_MODEL_VERSION: 'deterministic-profit-model.v1.0.0'
  }
},
   {
      name: 'profit-decision-drainer',
      script: './dist/workers/profitDecisionDrainer.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      kill_timeout: 10000,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/srv/arb-system/api/logs/pm2/profit-decision-drainer.out.log',
      error_file: '/srv/arb-system/api/logs/pm2/profit-decision-drainer.err.log',
      merge_logs: true,
    },
    {
      name: 'phase2-hardening-worker',
      script: 'dist/workers/phase2HardeningWorker.js',
      cwd: '/srv/arb-system/api',
      node_args: '-r dotenv/config',
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production' }
    },
    {
      name: 'prong2-comp-set-grounding-worker',
      script: 'dist/workers/prong2CompSetGroundingWorker.js',
      cwd: '/srv/arb-system/api',
      node_args: '-r dotenv/config',
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production' }
    },
    {
      name: 'catalog-enrichment-worker',
      script: './dist/workers/catalogEnrichmentWorker.js',
      node_args: '-r dotenv/config',
      cwd: '/srv/arb-system/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      kill_timeout: 10000,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        CATALOG_ENRICHMENT_RATE_LIMIT_MS: '1000',
        CATALOG_ENRICHMENT_BATCH_SIZE: '10',
        CATALOG_ENRICHMENT_MIN_TITLE_SIM: '0.40',
      },
      out_file: '/srv/arb-system/api/logs/pm2/catalog-enrichment-worker.out.log',
      error_file: '/srv/arb-system/api/logs/pm2/catalog-enrichment-worker.err.log',
      merge_logs: true,
    },
{
  name: 'watchlist-identity-janitor',
  script: 'dist/scripts/backfillWatchlistIdentity.js',
  node_args: '-r dotenv/config',
  cron_restart: '*/15 * * * *',
  autorestart: false,    // run once per cron tick, then stop
  max_memory_restart: '256M',
}

  ],
};
