import type { HubDecisionStatus } from "../models/protectionDecision";

export type AuthorityRole = "SYSTEM" | "SHIPPING_SUPERVISOR" | "OPERATIONS_MANAGER" | "EXECUTIVE";

export const decisionAuthorityMatrix: Record<HubDecisionStatus, readonly AuthorityRole[]> = {
  BYPASS: ["SYSTEM"],
  ALLOW: ["SYSTEM", "SHIPPING_SUPERVISOR", "OPERATIONS_MANAGER", "EXECUTIVE"],
  ALLOW_WITH_REQUIREMENTS: ["SYSTEM", "SHIPPING_SUPERVISOR", "OPERATIONS_MANAGER", "EXECUTIVE"],
  HOLD: ["OPERATIONS_MANAGER", "EXECUTIVE"],
  REPRICE: ["SHIPPING_SUPERVISOR", "OPERATIONS_MANAGER", "EXECUTIVE"],
  REQUOTE: ["SYSTEM", "SHIPPING_SUPERVISOR", "OPERATIONS_MANAGER", "EXECUTIVE"],
  MANUAL_REVIEW: ["SHIPPING_SUPERVISOR", "OPERATIONS_MANAGER", "EXECUTIVE"],
  REJECT: ["EXECUTIVE"]
};
