import type { Pool,PoolClient } from 'pg';
export interface VerificationClaim { artifactId:string;chainId:string;bucket:string;key:string;declaredSizeBytes:number;declaredContentType:string;clientSha256?:string;claimToken:string; }
export class ForensicStorageRepository { constructor(private readonly pool:Pool){}
 async claimVerification(artifactId:string,seconds:number,actorId:string):Promise<VerificationClaim>{const r=await this.pool.query('SELECT * FROM forensic.claim_artifact_verification($1,$2,$3)',[artifactId,seconds,actorId]);const x=r.rows[0];if(!x)throw new Error('verification claim not created');return {artifactId:x.artifact_id,chainId:x.chain_id,bucket:x.bucket_name,key:x.object_key,declaredSizeBytes:Number(x.declared_size_bytes),declaredContentType:x.declared_content_type,...(x.client_sha256?{clientSha256:x.client_sha256}:{}),claimToken:x.claim_token};}
 async finalizeVerification(i:{artifactId:string;claimToken:string;sha256:string;sizeBytes:number;contentType:string;etag?:string;versionId?:string;scanner:string;scannerResult:Record<string,unknown>;actorId:string;correlationId?:string}):Promise<void>{await this.pool.query('SELECT forensic.finalize_artifact_verification($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[i.artifactId,i.claimToken,i.sha256,i.sizeBytes,i.contentType,i.etag??null,i.versionId??null,i.scanner,i.scannerResult,i.actorId,i.correlationId??null]);}
 async quarantine(i:{artifactId:string;claimToken:string;key:string;etag?:string;versionId?:string;reason:string;actorId:string;correlationId?:string}):Promise<void>{await this.pool.query('SELECT forensic.quarantine_artifact($1,$2,$3,$4,$5,$6,$7,$8)',[i.artifactId,i.claimToken,i.key,i.etag??null,i.versionId??null,i.reason,i.actorId,i.correlationId??null]);}
 async createProcessRun(processName:string,entityPk:string,correlationId?:string):Promise<string>{const r=await this.pool.query(`INSERT INTO arb.process_runs(process_name,status,correlation_id,actor_type,actor_id,entity_type,entity_count,details_json) VALUES($1,'STARTED',$2,'worker','domain7-storage-worker','forensic_artifact',1,jsonb_build_object('entityPk',$3)) RETURNING run_id`,[processName,correlationId??null,entityPk]);return r.rows[0].run_id;}
 async completeProcessRun(runId:string,status:'SUCCEEDED'|'FAILED',details:Record<string,unknown>):Promise<void>{await this.pool.query(`UPDATE arb.process_runs SET status=$2,completed_at=CASE WHEN $2='SUCCEEDED' THEN clock_timestamp() ELSE completed_at END,failed_at=CASE WHEN $2='FAILED' THEN clock_timestamp() ELSE failed_at END,details_json=details_json||$3::jsonb,updated_at=clock_timestamp() WHERE run_id=$1`,[runId,status,details]);}
 async withClient<T>(fn:(c:PoolClient)=>Promise<T>):Promise<T>{const c=await this.pool.connect();try{return await fn(c);}finally{c.release();}}
}
