import type{Pool}from'pg';
import type{ForensicActorType}from'../models/orchestrationTypes';
export class ForensicOrchestrationRepository{
 constructor(private readonly pool:Pool){}
 async createChain(i:{tenantKey:string;chainType:string;policyVersionId?:string;retentionPolicyId?:string;metadata:Record<string,unknown>;actorType:ForensicActorType;actorId:string;actorName?:string;idempotencyKey:string;processRunId?:string;correlationId:string}){const r=await this.pool.query('SELECT * FROM forensic.create_chain_idempotent($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[i.tenantKey,i.chainType,i.policyVersionId??null,i.retentionPolicyId??null,i.metadata,i.actorType,i.actorId,i.actorName??null,i.idempotencyKey,i.processRunId??null,i.correlationId]);return r.rows[0];}
 async getChain(chainId:string,tenantKey:string){const r=await this.pool.query('SELECT * FROM forensic.v_chain_output WHERE chain_id=$1 AND tenant_key=$2',[chainId,tenantKey]);return r.rows[0]??null;}
 async timeline(chainId:string,tenantKey:string){const r=await this.pool.query('SELECT e.* FROM forensic.custody_events e JOIN forensic.chains c ON c.chain_id=e.chain_id WHERE e.chain_id=$1 AND c.tenant_key=$2 ORDER BY e.sequence_number',[chainId,tenantKey]);return r.rows;}
 async assess(i:{chainId:string;tenantKey:string;stageCode:string;actorId:string;processRunId?:string}){const own=await this.getChain(i.chainId,i.tenantKey);if(!own)return null;const r=await this.pool.query('SELECT * FROM forensic.calculate_stage_assessment($1,$2,$3,$4)',[i.chainId,i.stageCode,i.actorId,i.processRunId??null]);return r.rows[0];}
 async transition(i:{chainId:string;tenantKey:string;toStage:string;actorType:ForensicActorType;actorId:string;actorName?:string;idempotencyKey:string;processRunId?:string;correlationId:string}){const r=await this.pool.query('SELECT * FROM forensic.request_chain_transition($1,$2,$3,$4,$5,$6,$7,$8,$9)',[i.chainId,i.tenantKey,i.toStage,i.actorType,i.actorId,i.actorName??null,i.idempotencyKey,i.processRunId??null,i.correlationId]);return r.rows[0];}
 async requestManifest(i:{chainId:string;tenantKey:string;manifestType:string;actorType:ForensicActorType;actorId:string;idempotencyKey:string;processRunId?:string;correlationId:string}){const r=await this.pool.query('SELECT * FROM forensic.request_manifest_build($1,$2,$3,$4,$5,$6,$7,$8)',[i.chainId,i.tenantKey,i.manifestType,i.actorType,i.actorId,i.idempotencyKey,i.processRunId??null,i.correlationId]);return r.rows[0];}
 async readiness(){const r=await this.pool.query("SELECT EXISTS(SELECT 1 FROM forensic.policy_versions WHERE status='ACTIVE' AND effective_from<=clock_timestamp() AND (effective_to IS NULL OR effective_to>clock_timestamp())) AS active_policy, to_regprocedure('forensic.append_custody_event(uuid,text,text,forensic.event_actor_type,text,text,text,jsonb,timestamptz,text,uuid,text,text)') IS NOT NULL AS a1, to_regprocedure('forensic.claim_artifact_verification(uuid,integer,text)') IS NOT NULL AS a2");return r.rows[0];}
}
