import type { CategoryPhotoRequirement } from '../models/photoTypes';

export const CATEGORY_PHOTO_PLAYBOOKS: CategoryPhotoRequirement[] = [
  { categoryPattern: 'phone|smartphone|iphone|android', requiredRoles: ['HERO','FRONT','BACK','SERIAL'], recommendedRoles: ['LEFT','RIGHT','DEFECT','ACCESSORY','PACKAGING'], serialEvidenceRequired: true, defectDisclosureRequired: true, minApprovedPhotos: 6, maxPhotos: 16, minHeroScore: 86, minSetScore: 84, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['text_remove','beautifier','uncrop','expand','generative_edit'] },
  { categoryPattern: 'laptop|macbook|notebook|computer', requiredRoles: ['HERO','FRONT','BACK','SERIAL'], recommendedRoles: ['LEFT','RIGHT','DEFECT','ACCESSORY','PACKAGING'], serialEvidenceRequired: true, defectDisclosureRequired: true, minApprovedPhotos: 7, maxPhotos: 18, minHeroScore: 85, minSetScore: 83, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['text_remove','beautifier','uncrop','expand','generative_edit'] },
  { categoryPattern: 'camera|dslr|mirrorless|lens', requiredRoles: ['HERO','FRONT','BACK','SERIAL'], recommendedRoles: ['TOP','BOTTOM','DEFECT','ACCESSORY'], serialEvidenceRequired: true, defectDisclosureRequired: true, minApprovedPhotos: 7, maxPhotos: 18, minHeroScore: 85, minSetScore: 84, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['text_remove','beautifier','uncrop','expand','generative_edit'] },
  { categoryPattern: 'shoe|sneaker|boot|footwear', requiredRoles: ['HERO','FRONT','BACK','BOTTOM'], recommendedRoles: ['LEFT','RIGHT','DEFECT','LABEL'], serialEvidenceRequired: false, defectDisclosureRequired: true, minApprovedPhotos: 8, maxPhotos: 18, minHeroScore: 85, minSetScore: 84, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['beautifier','generative_edit'] },
  { categoryPattern: 'tool|drill|saw|impact|battery', requiredRoles: ['HERO','FRONT','BACK','SERIAL'], recommendedRoles: ['ACCESSORY','DEFECT','PACKAGING'], serialEvidenceRequired: true, defectDisclosureRequired: true, minApprovedPhotos: 6, maxPhotos: 16, minHeroScore: 82, minSetScore: 80, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['text_remove','beautifier','generative_edit'] },
  { categoryPattern: 'jewelry|watch|ring|gold|silver', requiredRoles: ['HERO','FRONT','BACK'], recommendedRoles: ['LABEL','DEFECT','PACKAGING'], serialEvidenceRequired: false, defectDisclosureRequired: true, minApprovedPhotos: 6, maxPhotos: 18, minHeroScore: 88, minSetScore: 86, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['beautifier','generative_edit','color_change'] },
  { categoryPattern: 'game|console|xbox|playstation|nintendo', requiredRoles: ['HERO','FRONT','BACK','SERIAL'], recommendedRoles: ['ACCESSORY','DEFECT','PACKAGING'], serialEvidenceRequired: true, defectDisclosureRequired: true, minApprovedPhotos: 6, maxPhotos: 16, minHeroScore: 84, minSetScore: 82, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['text_remove','beautifier','generative_edit'] },
  { categoryPattern: 'network|router|switch|server|enterprise', requiredRoles: ['HERO','FRONT','BACK','SERIAL'], recommendedRoles: ['LABEL','ACCESSORY','DEFECT'], serialEvidenceRequired: true, defectDisclosureRequired: true, minApprovedPhotos: 6, maxPhotos: 16, minHeroScore: 82, minSetScore: 82, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['text_remove','beautifier','generative_edit'] },
  { categoryPattern: '.*', requiredRoles: ['HERO','FRONT','BACK'], recommendedRoles: ['DEFECT','ACCESSORY','PACKAGING'], serialEvidenceRequired: false, defectDisclosureRequired: true, minApprovedPhotos: 5, maxPhotos: 14, minHeroScore: 82, minSetScore: 80, allowedAiEdits: ['background_remove','resize','shadow'], forbiddenAiEdits: ['beautifier','generative_edit'] }
];

export function getCategoryPhotoPlaybook(categoryKey?: string): CategoryPhotoRequirement {
  const key = (categoryKey || 'generic').toLowerCase();
  return CATEGORY_PHOTO_PLAYBOOKS.find(p => new RegExp(p.categoryPattern, 'i').test(key)) ?? CATEGORY_PHOTO_PLAYBOOKS[CATEGORY_PHOTO_PLAYBOOKS.length - 1]!;
}
