export const UPS_SERVICE_CODES = { NEXT_DAY_AIR:"01", SECOND_DAY_AIR:"02", GROUND:"03", WORLDWIDE_EXPRESS:"07", WORLDWIDE_EXPEDITED:"08", STANDARD:"11", THREE_DAY_SELECT:"12", NEXT_DAY_AIR_SAVER:"13", NEXT_DAY_AIR_EARLY:"14", WORLDWIDE_EXPRESS_PLUS:"54", SECOND_DAY_AIR_AM:"59", UPS_SAVER:"65" } as const;
export const UPS_PACKAGE_CODES = { CUSTOMER_SUPPLIED_PACKAGE:"02", UPS_LETTER:"01", TUBE:"03", PAK:"04", EXPRESS_BOX:"21" } as const;
export const UPS_TRACKING_USER_AGENT = "UPSPubSubTrackingService";
export const UPS_TRANSIENT_ERROR_CODES = new Set(["10004", "VSS100"]);
export const UPS_HARD_AUTH_CODES = new Set(["UJ0001", "250002", "251004"]);
