export const USPS_EXTRA_SERVICES = {
  TRACKING: 920,
  SIGNATURE_CONFIRMATION: 921,
  ADULT_SIGNATURE_REQUIRED: 922,
  ADULT_SIGNATURE_RESTRICTED_DELIVERY: 923,
  SIGNATURE_CONFIRMATION_RESTRICTED_DELIVERY: 924,
  PRIORITY_MAIL_EXPRESS_INSURANCE: 925,
  INSURANCE_UP_TO_500: 930,
  INSURANCE_OVER_500: 931,
  INSURANCE_RESTRICTED_DELIVERY: 934,
  RETURN_RECEIPT: 955,
  RETURN_RECEIPT_ELECTRONIC: 957,
  PRIORITY_MAIL_EXPRESS_PO_TO_ADDRESSEE: 986,
} as const;
export function uspsInsuranceExtraServiceForValue(itemValue: number): number | undefined {
  if (itemValue <= 0) return undefined;
  return itemValue <= 500 ? USPS_EXTRA_SERVICES.INSURANCE_UP_TO_500 : USPS_EXTRA_SERVICES.INSURANCE_OVER_500;
}
