import type{Pool}from'pg';import type{CasefilePrincipal,CreateDossierInput,SignResult}from'../models/casefileTypes';
export class DossierRepository{constructor(private readonly pool:Pool){}
 async create(p:CasefilePrincipal,i:CreateDossierInput,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_create_dossier_r2($1::uuid,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::uuid,$12::uuid,$13::uuid,$14::forensic.event_actor_type,$15,$16,$17::uuid,$18::uuid)`,[i.chainId,p.tenantKey,i.dossierCode,i.purpose,i.subjectType,i.subjectReference,i.includeRetail,i.includeArb,i.includeWarehouse,i.includeForensic,i.legalHoldId,i.preservationVerificationId,p.warehouseUserId,p.actorType,p.actorId,i.idempotencyKey,c,run]);return rows[0]}
 async assemble(p:CasefilePrincipal,id:string,snapshotAt:string,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_assemble_dossier_r2($1::uuid,$2,$3::timestamptz,$4,$5::forensic.event_actor_type,$6::uuid,$7::uuid)`,[id,p.tenantKey,snapshotAt,p.actorId,p.actorType,run,c]);return rows[0]}
 async review(p:CasefilePrincipal,i:{versionId:string;result:string;checklistVersion:string;findings:unknown[]},run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_review_dossier($1::uuid,$2,$3,$4,$5::jsonb,$6::uuid,$7::uuid,$8::uuid,$9::uuid)`,[i.versionId,p.tenantKey,i.result,i.checklistVersion,JSON.stringify(i.findings),p.warehouseUserId,p.warehouseAuthSessionId,run,c]);return rows[0]}
 async createSigningRequest(p:CasefilePrincipal,versionId:string,provider:string,keyRef:string,keyVersion:string|undefined,alg:string,key:string,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_create_signing_request($1::uuid,$2,$3,$4,$5,$6,$7,$8::uuid,$9::uuid)`,[versionId,p.tenantKey,provider,keyRef,keyVersion??null,alg,key,run,c]);return rows[0]}
 async finalizeSeal(p:CasefilePrincipal,requestId:string,s:SignResult,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_finalize_seal($1::uuid,$2,$3,$4,$5,$6,$7,$8::timestamptz,$9::uuid,$10::uuid,$11::uuid,$12::uuid)`,[requestId,p.tenantKey,s.signatureBase64,s.publicKeyReference,s.certificateChainReference??null,s.timestampAuthorityReference??null,s.providerResponseSha256,s.signedAt,p.warehouseUserId,p.warehouseAuthSessionId,run,c]);return rows[0]}
 async assessRedaction(p:CasefilePrincipal,versionId:string,policy:string,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_assess_redaction($1::uuid,$2,$3,$4,$5::uuid,$6::uuid)`,[versionId,p.tenantKey,policy,p.actorId,run,c]);return rows[0]}
 async export(p:CasefilePrincipal,i:{dossierId:string;sealId:string;redactionAssessmentId:string;recipientAuthorizationId:string;exportArtifactId:string;idempotencyKey:string},run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_export_disclosure_r2($1::uuid,$2,$3::uuid,$4::uuid,$5::uuid,$6::uuid,$7::uuid,$8::uuid,$9,$10::uuid,$11::uuid)`,[i.dossierId,p.tenantKey,i.sealId,i.redactionAssessmentId,i.recipientAuthorizationId,i.exportArtifactId,p.warehouseUserId,p.warehouseAuthSessionId,i.idempotencyKey,run,c]);return rows[0]}
 async verify(p:CasefilePrincipal,id:string,sealId:string,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f2_verify_dossier_r2($1::uuid,$2,$3::uuid,$4,$5::forensic.event_actor_type,$6::uuid,$7::uuid)`,[id,p.tenantKey,sealId,p.actorId,p.actorType,run,c]);return rows[0]}
 async get(p:CasefilePrincipal,id:string){const{rows}=await this.pool.query(`SELECT d.*,COALESCE((SELECT jsonb_agg(v ORDER BY v.version_number)FROM forensic.case_dossier_versions v WHERE v.case_dossier_id=d.case_dossier_id),'[]')versions,COALESCE((SELECT jsonb_agg(s ORDER BY s.seal_version)FROM forensic.case_dossier_seals s WHERE s.case_dossier_id=d.case_dossier_id),'[]')seals FROM forensic.case_dossiers d WHERE d.case_dossier_id=$1::uuid AND d.tenant_key=$2`,[id,p.tenantKey]);return rows[0]??null}
}
