import type{Pool}from'pg';import type{AddHoldScopeInput,CasefilePrincipal,DecideHoldReleaseInput,OpenLegalHoldInput,RequestHoldReleaseInput,StorageVerificationObservation}from'../models/casefileTypes';
export class LegalHoldRepository{constructor(private readonly pool:Pool){}
 async open(p:CasefilePrincipal,i:OpenLegalHoldInput,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f1_open_hold($1::uuid,$2,$3,$4,$5,$6,$7,$8::timestamptz,$9::timestamptz,$10::uuid,$11::uuid,$12::forensic.event_actor_type,$13,$14,$15::uuid,$16::uuid)`,[i.chainId,p.tenantKey,i.holdCode,i.holdType,i.title,i.reason,i.authorityReference??null,i.effectiveAt,i.expiresAt??null,p.warehouseUserId,p.warehouseAuthSessionId,p.actorType,p.actorId,i.idempotencyKey,c,run]);return rows[0]}
 async addScope(p:CasefilePrincipal,i:AddHoldScopeInput,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f1_add_scope($1::uuid,$2,$3,$4,$5,$6::uuid,$7::forensic.event_actor_type,$8,$9,$10::uuid,$11::uuid)`,[i.legalHoldId,p.tenantKey,i.scopeType,i.scopeReference,i.includeDescendants,p.warehouseUserId,p.actorType,p.actorId,i.idempotencyKey,c,run]);return rows[0]}
 async materialize(p:CasefilePrincipal,scopeId:string,key:string,run:string,c:string){const{rows}=await this.pool.query(`SELECT forensic.d7f1_materialize_scope_r2($1::uuid,$2,$3,$4::forensic.event_actor_type,$5,$6::uuid,$7::uuid) member_count`,[scopeId,p.tenantKey,p.actorId,p.actorType,key,run,c]);return rows[0]}
 async recordStorageObservation(o:StorageVerificationObservation,run:string,c:string){const{rows}=await this.pool.query(`INSERT INTO forensic.storage_preservation_attestations(legal_hold_artifact_member_id,verification_version,adapter_name,adapter_version,object_exists,observed_sha256,observed_storage_version_id,object_lock_status,retention_until,replication_status,archive_retrievable,provider_response_sha256,result,observed_at,process_run_id,correlation_id) SELECT $1::uuid,COALESCE(max(verification_version),0)+1,$2,$3,$4,$5,$6,$7,$8::timestamptz,$9,$10,$11,CASE WHEN NOT $4 THEN 'NOT_FOUND' WHEN $5 IS NULL THEN 'PROVIDER_ERROR' ELSE 'VERIFIED' END,$12::timestamptz,$13::uuid,$14::uuid FROM forensic.storage_preservation_attestations WHERE legal_hold_artifact_member_id=$1::uuid RETURNING *`,[o.memberId,o.adapterName,o.adapterVersion,o.objectExists,o.observedSha256??null,o.observedStorageVersionId??null,o.objectLockStatus??null,o.retentionUntil??null,o.replicationStatus??null,o.archiveRetrievable??null,o.providerResponseSha256,o.observedAt,run,c]);return rows[0]}
 async verify(p:CasefilePrincipal,id:string,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f1_verify_preservation_r2($1::uuid,$2,$3,$4::forensic.event_actor_type,$5::uuid,$6::uuid)`,[id,p.tenantKey,p.actorId,p.actorType,run,c]);return rows[0]}
 async requestRelease(p:CasefilePrincipal,i:RequestHoldReleaseInput,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f1_request_release($1::uuid,$2,$3,$4::uuid,$5::uuid,$6::jsonb,$7,$8::uuid,$9::uuid)`,[i.legalHoldId,p.tenantKey,i.reason,p.warehouseUserId,p.warehouseAuthSessionId,JSON.stringify(i.conflictCheck),i.idempotencyKey,run,c]);return rows[0]}
 async decideRelease(p:CasefilePrincipal,i:DecideHoldReleaseInput,run:string,c:string){const{rows}=await this.pool.query(`SELECT * FROM forensic.d7f1_decide_release($1::uuid,$2,$3,$4,$5::uuid,$6::uuid,$7::uuid,$8::uuid,$9::uuid,$10::uuid)`,[i.releaseRequestId,p.tenantKey,i.decision,i.reason,p.warehouseUserId,p.warehouseAuthSessionId,i.verificationId,i.warehouseOverrideId??null,run,c]);return rows[0]}
 async get(p:CasefilePrincipal,id:string){const{rows}=await this.pool.query(`SELECT h.*,COALESCE((SELECT jsonb_agg(s ORDER BY s.created_at)FROM forensic.legal_hold_scopes s WHERE s.legal_hold_id=h.legal_hold_id),'[]')scopes,COALESCE((SELECT jsonb_agg(v ORDER BY v.verification_version)FROM forensic.preservation_verifications v WHERE v.legal_hold_id=h.legal_hold_id),'[]')verifications FROM forensic.legal_holds h WHERE h.legal_hold_id=$1::uuid AND h.tenant_key=$2`,[id,p.tenantKey]);return rows[0]??null}
}
