import { CopyObjectCommand,GetObjectCommand,HeadObjectCommand,ListObjectsV2Command,PutObjectCommand,S3Client } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { Readable } from 'node:stream';
import type { EvidenceStorageProvider } from '../models/storageTypes';
function encodedCopySource(bucket:string,key:string,versionId?:string):string { const path=key.split('/').map(encodeURIComponent).join('/'); return `${encodeURIComponent(bucket)}/${path}${versionId?`?versionId=${encodeURIComponent(versionId)}`:''}`; }
export class CloudflareR2Provider implements EvidenceStorageProvider {
 private readonly client:S3Client;
 constructor(accountId:string,accessKeyId:string,secretAccessKey:string){this.client=new S3Client({region:'auto',endpoint:`https://${accountId}.r2.cloudflarestorage.com`,credentials:{accessKeyId,secretAccessKey},forcePathStyle:true});}
 issuePutUrl(i:{bucket:string;key:string;contentType:string;sizeBytes:number;expiresSeconds:number;metadata:Record<string,string>}):Promise<string>{return getSignedUrl(this.client,new PutObjectCommand({Bucket:i.bucket,Key:i.key,ContentType:i.contentType,ContentLength:i.sizeBytes,Metadata:i.metadata}),{expiresIn:i.expiresSeconds});}
 issueGetUrl(i:{bucket:string;key:string;versionId?:string;expiresSeconds:number}):Promise<string>{return getSignedUrl(this.client,new GetObjectCommand({Bucket:i.bucket,Key:i.key,...(i.versionId?{VersionId:i.versionId}:{})}),{expiresIn:i.expiresSeconds});}
 async head(i:{bucket:string;key:string;versionId?:string}){const r=await this.client.send(new HeadObjectCommand({Bucket:i.bucket,Key:i.key,...(i.versionId?{VersionId:i.versionId}:{})}));return {sizeBytes:r.ContentLength??0,...(r.ContentType?{contentType:r.ContentType}:{}),...(r.ETag?{etag:r.ETag}:{}),...(r.VersionId?{versionId:r.VersionId}:{}),metadata:r.Metadata??{}};}
 async get(i:{bucket:string;key:string;versionId?:string}){const r=await this.client.send(new GetObjectCommand({Bucket:i.bucket,Key:i.key,...(i.versionId?{VersionId:i.versionId}:{})}));if(!r.Body)throw new Error('R2 object body missing');const stream=r.Body instanceof Readable?r.Body:Readable.fromWeb(r.Body.transformToWebStream() as never);return {stream,sizeBytes:r.ContentLength??0,...(r.ContentType?{contentType:r.ContentType}:{}),...(r.ETag?{etag:r.ETag}:{}),...(r.VersionId?{versionId:r.VersionId}:{}),metadata:r.Metadata??{}};}
 async copy(i:{bucket:string;sourceKey:string;sourceVersionId?:string;destinationKey:string;metadata:Record<string,string>}){const r=await this.client.send(new CopyObjectCommand({Bucket:i.bucket,Key:i.destinationKey,CopySource:encodedCopySource(i.bucket,i.sourceKey,i.sourceVersionId),MetadataDirective:'REPLACE',Metadata:i.metadata}));return {...(r.CopyObjectResult?.ETag?{etag:r.CopyObjectResult.ETag}:{}),...(r.VersionId?{versionId:r.VersionId}:{})};}
 async list(i:{bucket:string;prefix:string;continuationToken?:string}){const r=await this.client.send(new ListObjectsV2Command({Bucket:i.bucket,Prefix:i.prefix,...(i.continuationToken?{ContinuationToken:i.continuationToken}:{})}));return {objects:(r.Contents??[]).flatMap(o=>o.Key?[{key:o.Key,sizeBytes:o.Size??0,...(o.ETag?{etag:o.ETag}:{})}]:[]),...(r.NextContinuationToken?{nextToken:r.NextContinuationToken}:{})};}
}
