BEGIN;
INSERT INTO operations.event_sources(source_key,domain_number,service_name,description) VALUES
('DOMAIN_1_ACQUISITION',1,'Acquisition Decision Engine','Acquisition events'),('DOMAIN_2_CAPITAL',2,'Capital Allocation Engine','Capital events'),('DOMAIN_3_SHIPPING',3,'Shipping Intelligence Engine','Shipping/carrier events'),('DOMAIN_4_LISTING',4,'Listing Intelligence Engine','Listing events'),('DOMAIN_5_PHOTO',5,'Product Photography Engine','Photo events'),('DOMAIN_6_WAREHOUSE',6,'Warehouse Intelligence Engine','Warehouse events'),('DOMAIN_7_FORENSIC',7,'Forensic Evidence Chain','Evidence events'),('DOMAIN_8_RETURNS',8,'Return & Dispute Defense','Return/dispute events'),('DOMAIN_9_AI',9,'AI Orchestration Layer','AI events'),('DOMAIN_10_OPERATIONS',10,'Notifications & Operations','Self-health/incidents') ON CONFLICT DO NOTHING;
INSERT INTO operations.event_types(event_type,description,default_severity,default_classification,incident_capable) VALUES
('BUY_A_PLUS','High-priority approved purchase opportunity','HIGH','CONFIDENTIAL',false),('WORKER_FAILURE','Production worker failure','HIGH','INTERNAL',true),('CARRIER_FAILURE','Carrier/provider failure','HIGH','INTERNAL',true),('DISPUTE_OPENED','Dispute opened','HIGH','CONFIDENTIAL',true),('RETURN_CREATED','Return created','NOTICE','CONFIDENTIAL',true),('SECURITY_INCIDENT','Security incident','EMERGENCY','RESTRICTED',true),('SERVICE_RECOVERED','Service recovered','NOTICE','INTERNAL',true),('DEAD_LETTER_CREATED','Notification exhausted safe retries','CRITICAL','INTERNAL',true) ON CONFLICT DO NOTHING;
INSERT INTO operations.notification_audiences(audience_key,description,audience_type) VALUES
('ALL_COMPANY','All authorized company personnel','DYNAMIC'),('EXECUTIVE_TEAM','Executive leadership','STATIC'),('OPERATIONS','Operations team','STATIC'),('SHIPPING_OPERATIONS','Shipping team','STATIC'),('RETURNS_DISPUTES','Return/dispute team','STATIC'),('ON_CALL_OPERATIONS','Current on-call rotation','ON_CALL') ON CONFLICT DO NOTHING;
INSERT INTO operations.channel_rate_limits VALUES('EMAIL',20,100,1000,true,clock_timestamp()),('SMS',60,1,1000,true,clock_timestamp()) ON CONFLICT(channel) DO NOTHING;
UPDATE operations.channel_controls SET enabled=false,emergency_stop=true,reason='Fail-closed pending live Green Tier 1 certification',changed_by='SEED' WHERE channel IN('EMAIL','SMS');
COMMIT;
