import type { ReturnSession, ReturnStage, ReturnType } from '../types/returnTypes';
const types:ReturnType[]=['CUSTOMER_REMORSE','DEFECTIVE','WRONG_ITEM','NOT_AS_DESCRIBED','SHIPPING_DAMAGE','RETURN_TO_SENDER','UNDELIVERABLE','REFUSED_DELIVERY','WARRANTY','MARKETPLACE_DISPUTE','FRAUD_SWAP','INTERNAL_TRANSFER','RECALL','REPAIR_RETURN'];
export function ReturnStagePanel({session,stage,onSubmit,busy}:{session:ReturnSession;stage:ReturnStage;onSubmit:(payload:Record<string,unknown>)=>void;busy:boolean}){switch(stage){case'IDENTIFY':return <div className="space-y-3"><label className="block text-sm font-black">Return type<select defaultValue={session.returnType??''} name="returnType" onChange={e=>onSubmit({returnType:e.target.value})} className="tcds-focus mt-1 min-h-12 w-full rounded-2xl border border-tcds-line bg-white px-3 text-base"><option value="" disabled>Select return type</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><p className="text-xs text-tcds-muted">The return type controls evidence, refund, claims, review, and disposition rules.</p></div>;
case'PACKAGE_INSPECTION':return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit(Object.fromEntries(f))}} className="space-y-3"><label className="block text-sm font-black">Package condition<select name="packageCondition" className="tcds-focus mt-1 min-h-12 w-full rounded-2xl border px-3"><option>INTACT</option><option>CRUSHED</option><option>WET</option><option>OPENED</option><option>RESEALED</option><option>TAMPERED</option></select></label><div className="grid grid-cols-2 gap-2">{['tamperSuspected','wetOrContaminated','emptyPackage','evidenceComplete'].map(x=><label key={x} className="rounded-xl bg-tcds-surface p-3 text-sm font-bold"><input type="checkbox" name={x} value="true" className="mr-2"/>{x.replaceAll(/([A-Z])/g,' $1')}</label>)}</div><button disabled={busy} className="min-h-12 w-full rounded-2xl bg-tcds-black font-black text-white">Save package inspection</button></form>;
case'CONTENTS':return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit(Object.fromEntries(f))}} className="space-y-3"><p className="text-sm text-tcds-muted">Reconcile every expected item, serialized identity, quantity, and component.</p><label className="block text-sm font-black">Scanned item or serial<input name="identifier" className="tcds-focus mt-1 min-h-12 w-full rounded-2xl border px-3 text-base"/></label><label className="block text-sm font-black">Quantity received<input name="quantityReceived" type="number" min="0" defaultValue="1" className="tcds-focus mt-1 min-h-12 w-full rounded-2xl border px-3"/></label><button disabled={busy} className="min-h-12 w-full rounded-2xl bg-tcds-black font-black text-white">Reconcile contents</button></form>;
case'EVIDENCE_COMPARE':return <div className="space-y-3"><p className="text-sm text-tcds-muted">Compare outbound packing evidence, return-package evidence, identifiers, and component photos.</p><button onClick={()=>onSubmit({compare:true})} disabled={busy} className="min-h-12 w-full rounded-2xl bg-tcds-black font-black text-white">Run evidence comparison</button></div>;
case'CONDITION_SAFETY':return <form onSubmit={e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.currentTarget)))}} className="space-y-3"><label className="block text-sm font-black">Returned condition<select name="conditionReturned" className="mt-1 min-h-12 w-full rounded-2xl border px-3"><option>EXCELLENT</option><option>GOOD</option><option>FAIR</option><option>DAMAGED</option><option>UNSAFE</option></select></label><label className="block text-sm font-black">Battery / safety<select name="batteryState" className="mt-1 min-h-12 w-full rounded-2xl border px-3"><option>NOT_APPLICABLE</option><option>NORMAL</option><option>SWOLLEN</option><option>LEAKING</option><option>UNKNOWN</option></select></label><div className="grid grid-cols-2 gap-2"><label className="rounded-xl bg-tcds-surface p-3 text-sm font-bold"><input type="checkbox" name="customerDataPresent" value="true" className="mr-2"/>Customer data present</label><label className="rounded-xl bg-tcds-surface p-3 text-sm font-bold"><input type="checkbox" name="activationLock" value="true" className="mr-2"/>Activation lock</label></div><button disabled={busy} className="min-h-12 w-full rounded-2xl bg-tcds-black font-black text-white">Save condition & safety</button></form>;
case'RISK_REVIEW':return <div className="space-y-3"><p className="text-sm text-tcds-muted">Run deterministic identity, safety, evidence, policy, and fraud checks. AI supports but does not replace the rules engine.</p><button onClick={()=>onSubmit({assess:true})} disabled={busy} className="min-h-12 w-full rounded-2xl bg-tcds-black font-black text-white">Run return assessment</button></div>;
case'DISPOSITION':return <div className="space-y-2">{session.permittedDispositions.map(o=><button key={o.outcome} disabled={!o.permitted||busy} onClick={()=>onSubmit({outcome:o.outcome})} className="tcds-focus w-full rounded-2xl border border-tcds-line p-3 text-left disabled:opacity-45"><span className="font-black">{o.label}</span><span className="block text-xs text-tcds-muted">Approval: {o.approvalLevel}{o.blockers.length?` · ${o.blockers.join(', ')}`:''}</span></button>)}</div>;
case'HANDOFF':return <div className="space-y-3"><p className="text-sm text-tcds-muted">Complete the disposition-specific handoff: Put-Away, quarantine, claim, repair, disposal, or Pack & Ship.</p><button onClick={()=>onSubmit({handoff:true})} disabled={busy} className="min-h-12 w-full rounded-2xl bg-tcds-black font-black text-white">Complete authorized handoff prerequisites</button></div>;
default:return <p className="text-sm text-tcds-muted">All stages are complete.</p>}}
