import{Router}from'express';import{z}from'zod';import{randomUUID}from'node:crypto';import{ForensicApiError}from'../errors/ForensicApiError';import type{AuthenticatedForensicPrincipal,ForensicRequestContext}from'../models/orchestrationTypes';import{ForensicChainService}from'../services/forensicChainService';import{ForensicOrchestrationRepository}from'../repositories/forensicOrchestrationRepository';
declare global{namespace Express{interface Request{forensicPrincipal?:AuthenticatedForensicPrincipal}}}
const idempotency=z.string().min(8).max(200);const uuid=z.string().uuid();
function context(req:any):ForensicRequestContext{if(!req.forensicPrincipal)throw new ForensicApiError(401,'UNAUTHENTICATED','Authenticated forensic principal required');return{principal:req.forensicPrincipal,correlationId:String(req.headers['x-correlation-id']??randomUUID())};}
export function createForensicChainRouter(service:ForensicChainService,repo:ForensicOrchestrationRepository){const r=Router();
 r.post('/chains',async(req,res,next)=>{try{const b=z.object({chainType:z.string().min(1).max(80),policyVersionId:uuid.optional(),retentionPolicyId:uuid.optional(),metadata:z.record(z.string(),z.unknown()).default({}),idempotencyKey:idempotency}).parse(req.body);res.status(201).json(await service.create(context(req),b));}catch(e){next(e);}});
 r.get('/chains/:chainId',async(req,res,next)=>{try{res.json(await service.get(context(req),uuid.parse(req.params.chainId)));}catch(e){next(e);}});
 r.get('/chains/:chainId/timeline',async(req,res,next)=>{try{res.json(await service.timeline(context(req),uuid.parse(req.params.chainId)));}catch(e){next(e);}});
 r.post('/chains/:chainId/assess/:stage',async(req,res,next)=>{try{res.json(await service.assess(context(req),uuid.parse(req.params.chainId),z.string().min(1).max(80).parse(req.params.stage)));}catch(e){next(e);}});
 r.post('/chains/:chainId/transition',async(req,res,next)=>{try{const b=z.object({toStage:z.string().min(1).max(80),idempotencyKey:idempotency}).parse(req.body);res.json(await service.transition(context(req),uuid.parse(req.params.chainId),b));}catch(e){next(e);}});
 r.post('/chains/:chainId/manifests',async(req,res,next)=>{try{const b=z.object({manifestType:z.string().min(1).max(100),idempotencyKey:idempotency}).parse(req.body);res.status(202).json(await service.requestManifest(context(req),uuid.parse(req.params.chainId),b));}catch(e){next(e);}});
 r.get('/health',(_req,res)=>res.json({status:'ok',domain:'forensic',slice:'7A.3-R2'}));
 r.get('/ready',async(_req,res,next)=>{try{const x=await repo.readiness();const ready=Boolean(x.active_policy&&x.a1&&x.a2);res.status(ready?200:503).json({status:ready?'ready':'not_ready',checks:x});}catch(e){next(e);}});return r;}
export function forensicErrorMiddleware(error:unknown,_req:any,res:any,next:any){if(error instanceof z.ZodError)return res.status(400).json({error:'VALIDATION_FAILED',details:error.issues});if(error instanceof ForensicApiError)return res.status(error.statusCode).json({error:error.code,message:error.message,details:error.details});const m=error instanceof Error?error.message:String(error);if(m.includes('idempotency key payload conflict'))return res.status(409).json({error:'IDEMPOTENCY_CONFLICT',message:m});if(m.includes('chain not found'))return res.status(404).json({error:'CHAIN_NOT_FOUND',message:m});return next(error);}
