import { getUpsEnv, UpsEnv } from "../config/upsEnv";
import { UpsOAuthTokenResponse } from "../models/upsTypes";
import { createUpsTransId } from "../utils/upsUtils";
export class UpsClientError extends Error { constructor(message: string, public readonly statusCode?: number, public readonly responseBody?: unknown) { super(message); this.name = "UpsClientError"; } }
export class UpsClient {
  private tokenCache?: UpsOAuthTokenResponse & { cachedAtMs: number };
  constructor(private readonly env: UpsEnv = getUpsEnv()) {}
  async healthCheck(): Promise<{ ok: boolean; carrier: "UPS"; auth: boolean; environment: string }> { if (!this.env.UPS_ENABLED) return { ok:false, carrier:"UPS", auth:false, environment:this.env.UPS_ENVIRONMENT }; const token = await this.getAccessToken(); return { ok:Boolean(token), carrier:"UPS", auth:Boolean(token), environment:this.env.UPS_ENVIRONMENT }; }
  async getJson<T>(path: string, query: Record<string, unknown> = {}, headers: Record<string,string> = {}): Promise<T> { const url = new URL(path, this.apiBaseUrl()); Object.entries(query).forEach(([k,v]) => { if (v!==undefined && v!==null && String(v).trim()!=="") url.searchParams.set(k,String(v)); }); return this.fetchWithRetry<T>(url.toString(), { method:"GET", headers: await this.authHeaders(headers) }); }
  async postJson<T>(path: string, body: unknown, headers: Record<string,string> = {}): Promise<T> { const url = new URL(path, this.apiBaseUrl()); return this.fetchWithRetry<T>(url.toString(), { method:"POST", headers:{ ...(await this.authHeaders(headers)), "Content-Type":"application/json" }, body: JSON.stringify(body) }); }
  async deleteJson<T>(path: string, query: Record<string,unknown> = {}, headers: Record<string,string> = {}): Promise<T> { const url = new URL(path, this.apiBaseUrl()); Object.entries(query).forEach(([k,v]) => { if (v!==undefined && v!==null && String(v).trim()!=="") url.searchParams.set(k,String(v)); }); return this.fetchWithRetry<T>(url.toString(), { method:"DELETE", headers: await this.authHeaders(headers) }); }
  async refreshToken(refreshToken=this.env.UPS_REFRESH_TOKEN): Promise<UpsOAuthTokenResponse> { if (!refreshToken) throw new UpsClientError("UPS_REFRESH_TOKEN is missing."); if (!this.env.UPS_CLIENT_ID || !this.env.UPS_CLIENT_SECRET) throw new UpsClientError("UPS_CLIENT_ID or UPS_CLIENT_SECRET is missing."); const credentials = Buffer.from(`${this.env.UPS_CLIENT_ID}:${this.env.UPS_CLIENT_SECRET}`).toString("base64"); const url = new URL("/v1/oauth/refresh", this.securityBaseUrl()); const body = new URLSearchParams({ grant_type:"refresh_token", refresh_token: refreshToken }); const token = await this.fetchWithRetry<UpsOAuthTokenResponse>(url.toString(), { method:"POST", headers:{ Authorization:`Basic ${credentials}`, Accept:"application/json", "Content-Type":"application/x-www-form-urlencoded" }, body }); this.tokenCache = { ...token, cachedAtMs: Date.now() }; return token; }
  private async getAccessToken(): Promise<string> { if (this.env.UPS_ACCESS_TOKEN) return this.env.UPS_ACCESS_TOKEN; const now=Date.now(); if (this.tokenCache?.access_token && this.tokenCache.expires_in) { const issuedAt=Number(this.tokenCache.issued_at ?? now); const expiresIn=Number(this.tokenCache.expires_in); if (now < issuedAt + Math.max(expiresIn - this.env.UPS_TOKEN_REFRESH_SKEW_SECONDS,60)*1000) return this.tokenCache.access_token; } const token=await this.refreshToken(); if (!token.access_token) throw new UpsClientError("UPS token response missing access_token."); return token.access_token; }
  private async authHeaders(extra: Record<string,string> = {}): Promise<Record<string,string>> { return { Authorization:`Bearer ${await this.getAccessToken()}`, Accept:"application/json", transId: extra.transId ?? createUpsTransId(this.env.UPS_TRANS_ID_PREFIX), transactionSrc: extra.transactionSrc ?? this.env.UPS_TRANSACTION_SRC, ...extra }; }
  private apiBaseUrl(): string { return this.env.UPS_ENVIRONMENT === "cie" ? this.env.UPS_CIE_BASE_URL : this.env.UPS_BASE_URL; }
  private securityBaseUrl(): string { return this.env.UPS_ENVIRONMENT === "cie" ? this.env.UPS_CIE_SECURITY_BASE_URL : this.env.UPS_SECURITY_BASE_URL; }
  private async fetchWithRetry<T>(url: string, init: RequestInit): Promise<T> { let lastError: unknown; for (let attempt=0; attempt<=this.env.UPS_MAX_RETRIES; attempt++) { const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(), this.env.UPS_TIMEOUT_MS); try { const response=await fetch(url,{...init, signal: controller.signal}); const ct=response.headers.get("content-type")||""; const body=ct.includes("application/json") ? await response.json().catch(()=>({})) : await response.text(); if (response.ok) return body as T; if (![429,500,503].includes(response.status) || attempt===this.env.UPS_MAX_RETRIES) throw new UpsClientError(`UPS API error ${response.status}`, response.status, body); } catch(error) { lastError=error; if (attempt===this.env.UPS_MAX_RETRIES) break; } finally { clearTimeout(timeout); } await new Promise((r)=>setTimeout(r,500*Math.pow(2,attempt))); } if (lastError instanceof Error) throw lastError; throw new UpsClientError("UPS API request failed."); }
}
