import crypto from "crypto";
import { UPS_HARD_AUTH_CODES, UPS_TRANSIENT_ERROR_CODES } from "../constants/upsConstants";
export function hashJson(value: unknown): string { return crypto.createHash("sha256").update(JSON.stringify(value ?? {})).digest("hex"); }
export function hashText(value: string): string { return crypto.createHash("sha256").update(value).digest("hex"); }
export function createUpsTransId(prefix = "TCDSUPS"): string { return `${prefix}${Date.now().toString(36).toUpperCase()}${crypto.randomBytes(6).toString("hex").toUpperCase()}`.slice(0,32); }
export function classifyUpsError(code?: string, httpStatus?: number): "TRANSIENT" | "HARD" | "UNKNOWN" { if (!code && !httpStatus) return "UNKNOWN"; if ((code && UPS_TRANSIENT_ERROR_CODES.has(code)) || [429,500,503].includes(httpStatus ?? 0)) return "TRANSIENT"; if ((code && UPS_HARD_AUTH_CODES.has(code)) || [400,401,403,404,405].includes(httpStatus ?? 0)) return "HARD"; return "UNKNOWN"; }
export function normalizeUpsMoney(value: unknown): number | undefined { if (typeof value === "number" && Number.isFinite(value)) return value; if (typeof value === "string" && value.trim() && !Number.isNaN(Number(value))) return Number(value); return undefined; }
export function parseUpsDateTime(date?: string, time?: string): string | undefined { if (!date || !/^\d{8}$/.test(date)) return undefined; const t = time && /^\d{6}$/.test(time) ? time : "000000"; return `${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${t.slice(0,2)}:${t.slice(2,4)}:${t.slice(4,6)}Z`; }
export function detectUpsTrackingRisk(statusDescription?: string): string { const text=(statusDescription ?? "").toUpperCase(); if (text.includes("DELIVERED")) return "DELIVERED"; if (text.includes("OUT FOR DELIVERY")) return "OUT_FOR_DELIVERY"; if (text.includes("EXCEPTION")) return "EXCEPTION"; if (text.includes("DELAY")) return "DELAYED"; if (text.includes("RETURN")) return "RETURN"; if (text.includes("HELD")) return "HELD"; return "NORMAL"; }
