import type {Pool,PoolClient} from 'pg';
import type {CapitalSafetyPolicy,Domain2CapitalProposal,ExposureSnapshot,ReadinessEvidence,CapitalSafetyDecision,FinancialState,PurchaseLifecycleEvidence,PurchaseLifecycleState,ExecutionRevalidationResult} from '../models/capitalSafetyTypes';

export class CapitalSafetyRepository{
  constructor(private readonly pool:Pool){}
  async withTransaction<T>(fn:(client:PoolClient)=>Promise<T>):Promise<T>{const c=await this.pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async lockEnvelope(client:PoolClient,currency:string):Promise<void>{await client.query(`select pg_advisory_xact_lock(hashtextextended($1,0))`,[`DOMAIN11F|${currency}`]);}

  async loadProposal(client:PoolClient,runId:number,sourceRecordId:string):Promise<Domain2CapitalProposal>{
    const q=await client.query(`select i.run_id,i.source_record_id,i.listing_id::text,i.candidate_id::text,i.category_key,i.family_key,i.capital_allocation_usd,i.required_capital_usd,i.allocation_json,r.completed_at,r.run_status from arb.capital_allocation_items i join arb.capital_allocation_runs r on r.id=i.run_id where i.run_id=$1 and i.source_record_id=$2 and r.run_status='completed'`,[runId,sourceRecordId]);
    if(q.rowCount!==1)throw Object.assign(new Error('DOMAIN2_CAPITAL_PROPOSAL_NOT_FOUND'),{statusCode:422});
    const x=q.rows[0] as Record<string,unknown>;const aj=(x.allocation_json??{}) as Record<string,unknown>;
    const decisionId=nullableText(aj.decisionId),listingId=nullableText(x.listing_id);
    const purchaseLifecycle=await this.loadPurchaseLifecycleEvidence(client,runId,sourceRecordId,decisionId,listingId);
    const acquisition=await this.loadCurrentAcquisitionEvidence(client,sourceRecordId);
    return {externalDecisionId:`domain2:${runId}:${sourceRecordId}`,capitalAllocationRunId:runId,sourceRecordId,decisionId,listingId,candidateId:nullableText(x.candidate_id),categoryKey:nullableText(x.category_key),familyKey:nullableText(x.family_key),skuKey:nullableText(aj.skuKey),supplierKey:nullableText(aj.supplierKey),marketplaceKey:nullableText(aj.marketplaceKey),requestedAmount:num(x.capital_allocation_usd),requiredCapital:num(x.required_capital_usd),currencyCode:String(aj.currencyCode??'USD').toUpperCase(),executionStatus:nullableText(aj.executionStatus),purchaseQueueStatus:nullableText(aj.purchaseQueueStatus),purchaseLifecycle,currentAcquisitionEvidence:acquisition.status,currentAcquisitionObservedAt:acquisition.observedAt,currentAcquisitionEvidenceReference:acquisition.reference,createdAt:new Date(String(x.completed_at))};
  }

  private async loadPurchaseLifecycleEvidence(client:PoolClient,runId:number,sourceRecordId:string,decisionId:string|null,listingId:string|null):Promise<PurchaseLifecycleEvidence>{
    const observedAt=new Date();
    const exists=await client.query<{exists:boolean}>(`select to_regclass('arb.purchase_queue') is not null as exists`);
    if(!exists.rows[0]?.exists)return {currentState:'UNKNOWN',currentQueueStatus:null,currentStatus:null,approvedAt:null,crossedSideEffectBoundary:null,duplicateIdentityConflict:null,reference:'arb.purchase_queue:MISSING',observedAt};
    const cols=await client.query<{column_name:string}>(`select column_name from information_schema.columns where table_schema='arb' and table_name='purchase_queue'`);const c=new Set(cols.rows.map(x=>x.column_name));
    const required=['capital_allocation_run_id','capital_allocation_source_record_id','queue_status','status','approved_at'];
    if(required.some(k=>!c.has(k)))return {currentState:'UNKNOWN',currentQueueStatus:null,currentStatus:null,approvedAt:null,crossedSideEffectBoundary:null,duplicateIdentityConflict:null,reference:`arb.purchase_queue:INSUFFICIENT_LIFECYCLE:${[...c].sort().join(',')}`,observedAt};
    const current=await client.query(`select queue_status::text,status::text,approved_at::timestamptz from arb.purchase_queue where capital_allocation_run_id=$1 and capital_allocation_source_record_id::text=$2 order by coalesce(approved_at,'epoch'::timestamptz) desc limit 2`,[runId,sourceRecordId]);
    if((current.rowCount??0)>1)return {currentState:'UNKNOWN',currentQueueStatus:null,currentStatus:null,approvedAt:null,crossedSideEffectBoundary:null,duplicateIdentityConflict:true,reference:`arb.purchase_queue:run:${runId}:source:${sourceRecordId}:MULTIPLE_CURRENT_ROWS`,observedAt};
    const row=current.rows[0] as Record<string,unknown>|undefined;
    const queueStatus=row?nullableText(row.queue_status):null,status=row?nullableText(row.status):null,approvedAt=row?.approved_at?new Date(String(row.approved_at)):null;
    const state=classifyLifecycle(queueStatus,status,approvedAt);
    const crossed=state==='UNKNOWN'?null:['RESERVED','COMMITTED','EXECUTING','EXECUTED','SETTLED'].includes(state);
    const identity=decisionId&&c.has('decision_id')?{column:'decision_id',value:decisionId}:listingId&&c.has('listing_id')?{column:'listing_id',value:listingId}:null;
    let duplicate:boolean|null=null;
    if(identity){const d=await client.query<{n:number}>(`select count(*)::int n from arb.purchase_queue where ${identity.column}::text=$1 and not (capital_allocation_run_id=$2 and capital_allocation_source_record_id::text=$3)`,[identity.value,runId,sourceRecordId]);duplicate=Number(d.rows[0]?.n??0)>0;}
    return {currentState:state,currentQueueStatus:queueStatus,currentStatus:status,approvedAt,crossedSideEffectBoundary:crossed,duplicateIdentityConflict:duplicate,reference:`arb.purchase_queue:run:${runId}:source:${sourceRecordId}`,observedAt};
  }

  private async loadCurrentAcquisitionEvidence(client:PoolClient,sourceRecordId:string):Promise<{status:'PASS'|'FAIL'|'UNKNOWN';observedAt:Date|null;reference:string}>{
    const exists=await client.query<{exists:boolean}>(`select to_regclass('arb.v_domain2_buy_qualified_source') is not null as exists`);if(!exists.rows[0]?.exists)return {status:'UNKNOWN',observedAt:null,reference:'arb.v_domain2_buy_qualified_source:MISSING'};
    const cols=await client.query<{column_name:string}>(`select column_name from information_schema.columns where table_schema='arb' and table_name='v_domain2_buy_qualified_source'`);const c=new Set(cols.rows.map(x=>x.column_name));
    const identity=c.has('source_record_id')?'source_record_id':c.has('id')?'id':c.has('decision_id')?'decision_id':null;const execution=c.has('execution_status')?'execution_status':null;const qualification=c.has('qualification_status')?'qualification_status':null;const decision=c.has('final_decision')?'final_decision':c.has('decision_status')?'decision_status':c.has('original_decision')?'original_decision':c.has('decision')?'decision':null;const created=c.has('created_at')?'created_at':null;
    if(!identity||!execution||!qualification||!decision)return {status:'UNKNOWN',observedAt:null,reference:`arb.v_domain2_buy_qualified_source:INSUFFICIENT_CONTRACT:${[...c].sort().join(',')}`};
    const q=await client.query(`select ${execution}::text execution_status,${qualification}::text qualification_status,${decision}::text decision_status,${created?`${created}::timestamptz`:'null::timestamptz'} observed_at from arb.v_domain2_buy_qualified_source where ${identity}::text=$1 limit 1`,[sourceRecordId]);
    if(q.rowCount!==1)return {status:'FAIL',observedAt:null,reference:`arb.v_domain2_buy_qualified_source:${identity}:${sourceRecordId}:NOT_CURRENT`};const r=q.rows[0] as Record<string,unknown>;const ok=String(r.qualification_status).toUpperCase()==='BUY_QUALIFIED'&&['AUTO_BUY_READY','BID_MONITOR_READY','REVIEW_REQUIRED'].includes(String(r.execution_status).toUpperCase())&&String(r.decision_status).toUpperCase().startsWith('BUY');return {status:ok?'PASS':'FAIL',observedAt:r.observed_at?new Date(String(r.observed_at)):null,reference:`arb.v_domain2_buy_qualified_source:${identity}:${sourceRecordId}`};
  }

  async loadPolicy(client:PoolClient):Promise<CapitalSafetyPolicy|null>{
    const q=await client.query(`select v.governance_policy_id,v.governance_policy_version_id,v.policy_sha256,v.configuration_sha256,v.effective_from,v.effective_until,c.configuration_document from arb.v_effective_policy_versions v join arb.policy_version_configurations c on c.governance_policy_version_id=v.governance_policy_version_id where v.policy_code='CAPITAL_SAFETY_POLICY' order by v.activated_at desc limit 1`);if(q.rowCount!==1)return null;const x=q.rows[0] as Record<string,unknown>;
    const comp=await client.query(`select component_id from arb.component_registry where component_code='DOMAIN11F_CAPITAL_SAFETY'`);const componentId=comp.rows[0]?.component_id as string|undefined;let drift:'MATCH'|'DRIFTED'|'UNKNOWN'|'UNAVAILABLE'='UNKNOWN',ack=false;
    if(componentId){const d=await client.query(`select o.drift_status from arb.configuration_observations o join arb.policy_consumer_bindings b on b.policy_consumer_binding_id=o.policy_consumer_binding_id where b.governance_policy_id=$1::uuid and b.consumer_component_id=$2::uuid order by o.observed_at desc,o.reported_at desc limit 1`,[x.governance_policy_id,componentId]);drift=(d.rows[0]?.drift_status??'UNKNOWN') as typeof drift;const a=await client.query(`select 1 from arb.policy_consumer_acknowledgements a join arb.policy_consumer_bindings b on b.policy_consumer_binding_id=a.policy_consumer_binding_id where b.governance_policy_id=$1::uuid and b.consumer_component_id=$2::uuid and a.governance_policy_version_id=$3::uuid and a.observed_policy_sha256=$4 limit 1`,[x.governance_policy_id,componentId,x.governance_policy_version_id,x.policy_sha256]);ack=(a.rowCount??0)>0;}
    return {governancePolicyId:String(x.governance_policy_id),governancePolicyVersionId:String(x.governance_policy_version_id),policySha256:String(x.policy_sha256),configurationSha256:String(x.configuration_sha256),effectiveFrom:x.effective_from?new Date(String(x.effective_from)):null,effectiveUntil:x.effective_until?new Date(String(x.effective_until)):null,configuration:(x.configuration_document??{}) as Record<string,unknown>,consumerDriftStatus:drift,consumerAcknowledged:ack};
  }

  async loadReadiness(client:PoolClient,componentId:string):Promise<ReadinessEvidence|null>{const q=await client.query(`select * from arb.v_effective_readiness_current where component_id=$1::uuid`,[componentId]);if(q.rowCount!==1)return null;const x=q.rows[0] as Record<string,unknown>;return {componentId,assessmentId:String(x.readiness_assessment_id),readinessState:String(x.readiness_state),canMutateState:Boolean(x.can_mutate_state),capitalTechnicalReadiness:Boolean(x.can_commit_capital),canCreateExternalSideEffects:Boolean(x.can_create_external_side_effects),evaluatedAt:new Date(String(x.evaluated_at)),validUntil:x.valid_until?new Date(String(x.valid_until)):null,expired:Boolean(x.expired)};}

  async loadExposure(client:PoolClient,proposal:Domain2CapitalProposal,financial:FinancialState):Promise<ExposureSnapshot>{
    const q=await client.query(`select coalesce(sum(c.requested_amount) filter(where c.valid_until>clock_timestamp() and c.assessment_state in('ALLOW','ALLOW_WITH_GUARD')),0)::numeric provisional,coalesce(sum(c.requested_amount) filter(where c.assessed_at>=date_trunc('day',clock_timestamp()) and c.assessment_state in('ALLOW','ALLOW_WITH_GUARD')),0)::numeric daily,coalesce(sum(c.requested_amount) filter(where p.category_key=$1 and c.valid_until>clock_timestamp() and c.assessment_state in('ALLOW','ALLOW_WITH_GUARD')),0)::numeric category,coalesce(sum(c.requested_amount) filter(where p.family_key=$2 and c.valid_until>clock_timestamp() and c.assessment_state in('ALLOW','ALLOW_WITH_GUARD')),0)::numeric family,coalesce(sum(c.requested_amount) filter(where p.sku_key=$3 and c.valid_until>clock_timestamp() and c.assessment_state in('ALLOW','ALLOW_WITH_GUARD')),0)::numeric sku,coalesce(sum(c.requested_amount) filter(where p.supplier_key=$4 and c.valid_until>clock_timestamp() and c.assessment_state in('ALLOW','ALLOW_WITH_GUARD')),0)::numeric supplier,coalesce(sum(c.requested_amount) filter(where p.marketplace_key=$5 and c.valid_until>clock_timestamp() and c.assessment_state in('ALLOW','ALLOW_WITH_GUARD')),0)::numeric marketplace from arb.capital_safety_current c join arb.capital_safety_provenance p using(capital_safety_assessment_id) where c.external_decision_id<>$6`,[proposal.categoryKey,proposal.familyKey,proposal.skuKey,proposal.supplierKey,proposal.marketplaceKey,proposal.externalDecisionId]);const x=q.rows[0] as Record<string,unknown>;
    const dims=await this.loadAuthoritativeDimensionExposure(client,proposal);
    return {provisionalAuthorized:num(x.provisional),dailyAuthorized:num(x.daily),authoritativeCapitalAtRisk:financial.authoritativeCapitalAtRisk??Number.NaN,categoryProvisional:num(x.category),familyProvisional:num(x.family),skuProvisional:num(x.sku),supplierProvisional:num(x.supplier),marketplaceProvisional:num(x.marketplace),categoryAuthoritative:dims.CATEGORY,familyAuthoritative:dims.FAMILY,skuAuthoritative:dims.SKU,supplierAuthoritative:dims.SUPPLIER,marketplaceAuthoritative:dims.MARKETPLACE};
  }

  private async loadAuthoritativeDimensionExposure(client:PoolClient,proposal:Domain2CapitalProposal):Promise<Record<'CATEGORY'|'FAMILY'|'SKU'|'SUPPLIER'|'MARKETPLACE',number|null>>{
    const out={CATEGORY:null,FAMILY:null,SKU:null,SUPPLIER:null,MARKETPLACE:null} as Record<'CATEGORY'|'FAMILY'|'SKU'|'SUPPLIER'|'MARKETPLACE',number|null>;
    const exists=await client.query<{exists:boolean}>(`select to_regclass('arb.v_domain2_financial_exposure_by_dimension') is not null as exists`);if(!exists.rows[0]?.exists)return out;
    const keys:{type:keyof typeof out,key:string|null}[]=[{type:'CATEGORY',key:proposal.categoryKey},{type:'FAMILY',key:proposal.familyKey},{type:'SKU',key:proposal.skuKey},{type:'SUPPLIER',key:proposal.supplierKey},{type:'MARKETPLACE',key:proposal.marketplaceKey}];
    for(const d of keys){if(!d.key)continue;const r=await client.query(`select capital_at_risk::numeric from arb.v_domain2_financial_exposure_by_dimension where currency_code=$1 and dimension_type=$2 and dimension_key=$3 order by observed_at desc limit 1`,[proposal.currencyCode,d.type,d.key]);if(r.rowCount===1)out[d.type]=num(r.rows[0]?.capital_at_risk);}
    return out;
  }

  async persistFailClosed(client:PoolClient,input:any):Promise<string>{return this.persistViaFunction(client,'domain11f_persist_fail_closed',input);}
  private async persistViaFunction(client:PoolClient,_name:string,input:any):Promise<string>{const p=input.proposal as Domain2CapitalProposal;const proposalJson=proposalJsonOf(p);const financialJson={...input.financial,observedAt:input.financial.observedAt.toISOString()};const q=await client.query<{id:string}>(`select arb.domain11f_persist_fail_closed($1,$2,$3,$4,$5,$6::text[],$7::jsonb,$8::jsonb,$9,$10,$11::uuid,$12) id`,[p.externalDecisionId,p.capitalAllocationRunId,p.sourceRecordId,p.requestedAmount,p.currencyCode,input.reasonCodes,JSON.stringify(proposalJson),JSON.stringify(financialJson),input.validUntil,input.idempotencyKey,input.correlationId,input.requestedBy]);return q.rows[0]!.id;}

  async persist(client:PoolClient,input:{proposal:Domain2CapitalProposal;financial:FinancialState;decision:CapitalSafetyDecision;policy:CapitalSafetyPolicy;readiness:ReadinessEvidence;correlationId:string;idempotencyKey:string;requestedBy:string;}):Promise<string>{const p=input.proposal;const controls=input.decision.controls.map(c=>({...c,evaluatedAt:c.evaluatedAt.toISOString()}));const q=await client.query<{id:string}>(`select arb.domain11f_persist_assessment($1,$2,$3,$4,$5,$6,$7::text[],$8::uuid,$9,$10,$11::uuid,$12::uuid,$13::jsonb,$14::jsonb,$15::jsonb,$16,$17,$18::uuid,$19) id`,[p.externalDecisionId,p.capitalAllocationRunId,p.sourceRecordId,p.requestedAmount,p.currencyCode,input.decision.evaluationState,input.decision.reasonCodes,input.policy.governancePolicyVersionId,input.policy.policySha256,input.policy.configurationSha256,input.readiness.componentId,input.readiness.assessmentId,JSON.stringify(proposalJsonOf(p)),JSON.stringify({...input.financial,observedAt:input.financial.observedAt.toISOString()}),JSON.stringify(controls),input.decision.validUntil,input.idempotencyKey,input.correlationId,input.requestedBy]);return q.rows[0]!.id;}

  async getCurrent(externalDecisionId:string){return (await this.pool.query(`select * from arb.v_effective_capital_safety_current where external_decision_id=$1`,[externalDecisionId])).rows[0]??null;}
  async revalidate(externalDecisionId:string):Promise<ExecutionRevalidationResult>{const q=await this.pool.query(`select * from arb.domain11f_revalidate_execution_eligibility($1)`,[externalDecisionId]);const x=q.rows[0];return {externalDecisionId,assessmentId:x?.capital_safety_assessment_id??null,eligible:Boolean(x?.eligible),reasonCodes:Array.isArray(x?.reason_codes)?x.reason_codes:[],checkedAt:new Date(String(x?.checked_at??new Date().toISOString()))};}
  async listRecent(limit:number){return (await this.pool.query(`select c.*,p.category_key,p.family_key,p.financial_completeness,p.governance_policy_version_id from arb.v_effective_capital_safety_current c join arb.capital_safety_provenance p using(capital_safety_assessment_id) order by c.assessed_at desc limit $1`,[limit])).rows;}
}

function classifyLifecycle(queueStatus:string|null,status:string|null,approvedAt:Date|null):PurchaseLifecycleState{const token=`${queueStatus??''}|${status??''}`.toUpperCase();if(/SETTLED|COMPLETED_SETTLEMENT/.test(token))return 'SETTLED';if(/EXECUTED|PURCHASED|COMPLETED|FULFILLED/.test(token))return 'EXECUTED';if(/EXECUTING|IN_PROGRESS|PROCESSING|SUBMITTED/.test(token))return 'EXECUTING';if(/COMMITTED|COMMIT/.test(token))return 'COMMITTED';if(/RESERVED|RESERVATION/.test(token))return 'RESERVED';if(/CANCELLED|CANCELED|VOID|REJECTED/.test(token))return 'CANCELLED';if(/RELEASED/.test(token))return 'RELEASED';if(/APPROVED|READY/.test(token)||approvedAt)return 'APPROVED';if(/QUEUED|PENDING/.test(token))return 'QUEUED';if(/PROPOSED|NEW|CREATED/.test(token))return 'PROPOSED';return 'UNKNOWN';}
function proposalJsonOf(p:Domain2CapitalProposal){return {capitalAllocationRunId:p.capitalAllocationRunId,sourceRecordId:p.sourceRecordId,externalDecisionId:p.externalDecisionId,requestedAmount:p.requestedAmount,requiredCapital:p.requiredCapital,currencyCode:p.currencyCode,decisionId:p.decisionId,listingId:p.listingId,candidateId:p.candidateId,categoryKey:p.categoryKey,familyKey:p.familyKey,skuKey:p.skuKey,supplierKey:p.supplierKey,marketplaceKey:p.marketplaceKey,executionStatus:p.executionStatus,purchaseQueueStatus:p.purchaseQueueStatus,purchaseLifecycle:{...p.purchaseLifecycle,approvedAt:p.purchaseLifecycle.approvedAt?.toISOString()??null,observedAt:p.purchaseLifecycle.observedAt.toISOString()},currentAcquisitionEvidence:p.currentAcquisitionEvidence,currentAcquisitionObservedAt:p.currentAcquisitionObservedAt?.toISOString()??null,currentAcquisitionEvidenceReference:p.currentAcquisitionEvidenceReference,createdAt:p.createdAt.toISOString()};}
function num(v:unknown):number{const n=Number(v);return Number.isFinite(n)?n:0;}function nullableText(v:unknown):string|null{return v===null||v===undefined||String(v).trim()===''?null:String(v);}
