import { useEffect,useMemo,useState } from 'react'; import { AppHeader } from '../../components/AppHeader'; import { ScreenCard } from '../../components/ScreenCard'; import { PrimaryButton } from '../../components/PrimaryButton'; import { ScanLine,Search,WifiOff,ShieldCheck,PackageOpen } from 'lucide-react';
import type { ReturnMessage,ReturnSession,ReturnStage,ReturnToast } from './types/returnTypes'; import { ReturnProgress } from './components/ReturnProgress'; import { ReturnGateCard } from './components/ReturnGateCard'; import { ReturnMessageCenter } from './components/ReturnMessageCenter'; import { ReturnMessageSheet } from './components/ReturnMessageSheet'; import { ReturnToastQueue } from './components/ReturnToastQueue'; import { ReturnGuidanceCard } from './components/ReturnGuidanceCard'; import { ReturnStagePanel } from './components/ReturnStagePanel'; import { returnsApi } from './services/returnsApi'; import { mapReturnError,sortReturnMessages } from './messages/returnMessageCatalog';
const guidance:Record<ReturnStage,{what:string;why:string;next:string}>={IDENTIFY:{what:'Scan the return package, authorization, order, tracking number, or TCDS item barcode, then classify the return type.',why:'Ownership, policy, evidence, refund, and claim rules depend on the authoritative order and return type.',next:'Claim the session and inspect the unopened package.'},PACKAGE_INSPECTION:{what:'Inspect the unopened package, seal, carrier label, damage, moisture, and tamper indicators. Capture required evidence.',why:'Package condition establishes chain of custody and supports fraud, carrier, and insurance decisions.',next:'Open the package and reconcile every expected item and component.'},CONTENTS:{what:'Scan each exact serialized item and reconcile quantity, bundle components, and accessories.',why:'A matching SKU is not enough for serialized arbitrage inventory.',next:'Compare outbound and return evidence.'},EVIDENCE_COMPARE:{what:'Run the evidence comparison and resolve any missing, blurred, or integrity-failed artifact.',why:'Disposition must be based on verified evidence, not memory or appearance alone.',next:'Complete condition, safety, contamination, and data-security checks.'},CONDITION_SAFETY:{what:'Grade condition and record battery, contamination, activation-lock, and customer-data findings.',why:'Safety and privacy requirements can prohibit restock, repair, shipping, or disposal.',next:'Run deterministic and intelligence risk review.'},RISK_REVIEW:{what:'Run identity, policy, evidence, safety, fraud, and financial-impact assessment.',why:'The system must calculate only the dispositions allowed by current facts and policy.',next:'Choose from the server-authorized dispositions.'},DISPOSITION:{what:'Select only a permitted disposition and provide the required justification or approval.',why:'Restock, quarantine, claim, repair, disposal, and return-to-customer have different gates.',next:'Complete the disposition-specific downstream handoff.'},HANDOFF:{what:'Complete all handoff prerequisites and create the downstream task or custody movement.',why:'Return intake is not complete until the physical item and financial/customer outcome have an owner.',next:'Run the authoritative completion gate.'},COMPLETE:{what:'Review the committed outcome and downstream work.',why:'The audit trail must show custody, financial resolution, and next owner.',next:'Return to the dashboard or open the generated task.'}};
export function ReturnsScreen(){
 const[session,setSession]=useState<ReturnSession|null>(null),[scan,setScan]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<ReturnMessage|null>(null),[toasts,setToasts]=useState<ReturnToast[]>([]),[online,setOnline]=useState(navigator.onLine);
 useEffect(()=>{const f=()=>setOnline(navigator.onLine);addEventListener('online',f);addEventListener('offline',f);return()=>{removeEventListener('online',f);removeEventListener('offline',f)}},[]);
 const messages=useMemo(()=>sortReturnMessages([...(session?.messages??[]),...(!online?[mapReturnError({code:'RETURN_OFFLINE'})]:[])]),[session,online]); const blocking=messages.some(m=>m.blocking); const ready=!!session&&session.gates.every(g=>g.state==='PASS'||g.state==='NA')&&!blocking;
 const toast=(m:ReturnMessage)=>setToasts(t=>[...t,{id:crypto.randomUUID(),message:m,createdAt:Date.now()}].slice(-3));
 async function run(fn:()=>Promise<ReturnSession>,success?:string){setBusy(true);try{const s=await fn();setSession(s);if(success)toast({code:'LOCAL_SUCCESS',severity:'SUCCESS',blocking:false,title:success,explanation:'The server committed the update.',nextStep:'Continue to the next required step.',dismissible:true});}catch(e){const m=mapReturnError(e as ReturnMessage);setSelected(m);setSession(s=>s?{...s,messages:[...s.messages,m]}:s)}finally{setBusy(false)}}
 async function resolve(){if(!scan.trim()||!online)return;await run(()=>returnsApi.resolveScan(scan.trim()),'Return matched')}
 async function submit(stage:ReturnStage,p:Record<string,unknown>){if(!session||!online)return;const id=session.returnSessionId,rv=session.rowVersion;
  if(stage==='IDENTIFY'&&p.returnType)return run(()=>returnsApi.classify(id,p.returnType as any,rv),'Return type classified');
  if(stage==='PACKAGE_INSPECTION')return run(()=>returnsApi.savePackageInspection(id,p,rv),'Package inspection saved');
  if(stage==='CONTENTS')return run(()=>returnsApi.reconcileContents(id,p,rv),'Contents reconciled');
  if(stage==='EVIDENCE_COMPARE')return run(()=>returnsApi.compareEvidence(id,rv),'Evidence comparison started');
  if(stage==='CONDITION_SAFETY')return run(()=>returnsApi.saveConditionSafety(id,p,rv),'Condition and safety saved');
  if(stage==='RISK_REVIEW')return run(()=>returnsApi.assess(id,rv),'Assessment queued');
  if(stage==='DISPOSITION'&&p.outcome)return run(()=>returnsApi.saveDisposition(id,p.outcome as any,'Authorized disposition selected after completed assessment',rv),'Disposition saved');
  if(stage==='HANDOFF')return run(()=>returnsApi.completePrerequisite(id,session.selectedDisposition??'REVIEW_REQUIRED',p,rv),'Handoff prerequisites updated');
 }
 async function complete(){if(!session||!ready)return;await run(()=>returnsApi.complete(session.returnSessionId,session.rowVersion),'Return completed')}
 return <><AppHeader title="Returns & Disposition" subtitle="Authorize, inspect, reconcile, contain, and route every returned item"/><ReturnToastQueue toasts={toasts} onDismiss={id=>setToasts(t=>t.filter(x=>x.id!==id))}/><div className="mx-auto max-w-md space-y-4 p-4 pb-28">
  {!online&&<div role="alert" className="flex gap-3 rounded-2xl border border-red-300 bg-red-50 p-4"><WifiOff className="text-red-700"/><div><p className="font-black">Offline — authoritative return actions are blocked.</p><p className="text-sm">Keep the item contained. Draft observations only until connectivity returns.</p></div></div>}
  <ReturnMessageCenter messages={messages} onSelect={setSelected}/>
  {!session?<><ScreenCard><div className="text-center"><ShieldCheck className="mx-auto text-tcds-gold" size={46}/><h2 className="mt-3 font-display text-xl font-black">Ready to receive a return</h2><p className="mt-1 text-sm text-tcds-muted">No return is loaded. Scan an authoritative package, authorization, tracking, order, or TCDS identifier.</p></div><div className="mt-4 flex gap-2"><div className="relative flex-1"><ScanLine className="absolute left-3 top-3.5 text-tcds-gold" size={20}/><input value={scan} onChange={e=>setScan(e.target.value)} className="tcds-focus min-h-12 w-full rounded-2xl border border-tcds-line pl-11 pr-3 text-base" placeholder="Scan or enter identifier" aria-label="Return identifier"/></div><button onClick={resolve} disabled={busy||!online||!scan.trim()} className="tcds-focus min-h-12 rounded-2xl bg-tcds-black px-4 text-white disabled:bg-neutral-300"><Search/></button></div></ScreenCard><ReturnGuidanceCard {...guidance.IDENTIFY}/></>:
  <><ScreenCard><ReturnProgress stage={session.stage}/></ScreenCard><ScreenCard><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-tcds-goldDeep">Return custody</p><h2 className="font-display text-xl font-black">{session.returnNumber}</h2><p className="text-sm text-tcds-muted">Order {session.orderNumber} · {session.facility} · {session.station}</p></div><PackageOpen className="text-tcds-gold"/></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-tcds-surface p-3"><p className="text-tcds-muted">Expected / verified</p><p className="font-black">{session.expectedItems} / {session.verifiedItems}</p></div><div className="rounded-xl bg-tcds-surface p-3"><p className="text-tcds-muted">Assessment</p><p className="font-black">{session.assessment.status}</p></div></div></ScreenCard><ReturnGuidanceCard {...guidance[session.stage]}/><ScreenCard><h3 className="mb-3 font-display text-lg font-black">Current workflow step</h3><ReturnStagePanel session={session} stage={session.stage} onSubmit={p=>submit(session.stage,p)} busy={busy}/></ScreenCard><ScreenCard><h3 className="mb-3 font-display text-lg font-black">Authoritative completion gates</h3><ReturnGateCard gates={session.gates} onSelect={g=>setSelected({code:g.code,severity:g.state==='FAIL'?'ERROR':'INFO',blocking:g.state==='FAIL',title:g.label,explanation:g.detail??`Gate status: ${g.state}`,nextStep:`Open the ${g.stage.replaceAll('_',' ').toLowerCase()} stage.`,destinationStage:g.stage,primaryAction:'OPEN_STAGE'})}/></ScreenCard><PrimaryButton onClick={complete} loading={busy} disabled={!ready}>Complete Return Intake & Commit Handoff</PrimaryButton></>}
 </div>{selected&&<ReturnMessageSheet message={selected} onClose={()=>setSelected(null)} onAction={m=>{setSelected(null);if(m.destinationStage&&session)setSession({...session,stage:m.destinationStage});}}/>}</>}
