import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, Barcode, Box, Camera, CheckCircle2, ClipboardCheck, PackageCheck, ScanLine, ShieldCheck, Sparkles } from 'lucide-react';
import { AppHeader } from '../../components/AppHeader';
import { PrimaryButton } from '../../components/PrimaryButton';
import { ScreenCard } from '../../components/ScreenCard';
import { ReceiveErrorBanner } from './components/ReceiveErrorBanner';
import { ReceiveProgress } from './components/ReceiveProgress';
import { ReceiptSessionBanner } from './components/ReceiptSessionBanner';
import { receivingApi } from './services/receivingApi';
import type { AllocatedBarcode, IntakeCandidate, IntakeItemDraft, IntakeVerificationResult, PackageCondition, ReceiptMatch, ReceiptSummary, ReceiveBootstrap, ReceivingSession, ReceiveStage } from './types/receivingTypes';

const emptyDraft = (receiptLineId = '', expectedTitle = ''): IntakeItemDraft => ({ receiptLineId, expectedTitle, upc: '', manufacturerPartNumber: '', serialNumber: '', condition: 'UNKNOWN', quantity: 1, employeeConfirmed: false });
const errorText: Record<string,string> = { SESSION_EXPIRED: 'Your secure session expired. Sign in again.', CONFLICT: 'This receipt or item changed on another device. Refresh before continuing.', EVIDENCE_REQUIRED: 'Required package evidence must be captured before continuing.', DUPLICATE_IDENTIFIER: 'The identifier is already assigned to another item.', REVIEW_REQUIRED: 'The intelligence engine requires supervisor review.' };

export function ReceiveScreen() {
  const navigate = useNavigate();
  const [stage, setStage] = useState<ReceiveStage>('SCAN_PACKAGE'); const [busy, setBusy] = useState(false); const [error, setError] = useState<string|null>(null);
  const [bootstrap, setBootstrap] = useState<ReceiveBootstrap|null>(null); const [identifier, setIdentifier] = useState(''); const [manual, setManual] = useState(false);
  const [receipt, setReceipt] = useState<ReceiptMatch|null>(null); const [session, setSession] = useState<ReceivingSession|null>(null); const [inboundPackageId, setInboundPackageId] = useState<string|null>(null);
  const [packageCondition, setPackageCondition] = useState<PackageCondition>('INTACT'); const [sealIntact, setSealIntact] = useState(true); const [visibleDamage, setVisibleDamage] = useState(false); const [carrierLabelClear, setCarrierLabelClear] = useState(true); const [evidenceAssetIds, setEvidenceAssetIds] = useState<string[]>([]);
  const [actualCount, setActualCount] = useState(1); const [lineIndex, setLineIndex] = useState(0); const [item, setItem] = useState<IntakeItemDraft>(emptyDraft()); const [candidate, setCandidate] = useState<IntakeCandidate|null>(null);
  const [verification, setVerification] = useState<IntakeVerificationResult>({ status: 'PENDING', confidence: null, reasons: [] }); const [barcode, setBarcode] = useState<AllocatedBarcode|null>(null); const [summary, setSummary] = useState<ReceiptSummary|null>(null);
  const requiresEvidence = visibleDamage || !sealIntact || packageCondition !== 'INTACT'; const canSubmit = useMemo(() => item.upc.trim().length >= 8 && item.condition !== 'UNKNOWN' && item.employeeConfirmed && (!receipt?.lines[lineIndex]?.requiresSerial || item.serialNumber.trim().length > 0), [item, receipt, lineIndex]);

  useEffect(() => { receivingApi.bootstrap().then(setBootstrap).catch(e => setError((e as Error).message)); }, []);
  useEffect(() => { if (!receipt?.lines[lineIndex]) return; const line = receipt.lines[lineIndex]; setItem(emptyDraft(line.receiptLineId, line.expectedTitle)); }, [receipt, lineIndex]);
  useEffect(() => { if (stage !== 'INTELLIGENCE_VERIFY' || !candidate) return; let stopped = false; const poll = async () => { try { const result = await receivingApi.verificationStatus(candidate.intakeCandidateId); if (stopped) return; setVerification(result); if (result.status === 'VERIFIED' || result.status === 'VERIFIED_WITH_WARNING') setStage('VERIFIED_FOR_INTAKE'); else if (result.status === 'REVIEW_REQUIRED') setStage('REVIEW_REQUIRED'); else if (result.status === 'REJECTED') setStage('REJECTED'); else window.setTimeout(poll, 2000); } catch (e) { if (!stopped) setError((e as Error).message); } }; void poll(); return () => { stopped = true; }; }, [stage, candidate]);

  const run = async (fn: () => Promise<void>) => { setBusy(true); setError(null); try { await fn(); } catch (e) { const code = (e as Error).message; if (code === 'SESSION_EXPIRED') navigate('/', { replace: true }); else setError(code); } finally { setBusy(false); } };
  const match = () => run(async () => { if (!identifier.trim()) throw new Error('Enter or scan a package identifier.'); const found = await receivingApi.matchPackage(identifier.trim()); setReceipt(found); setActualCount(found.expectedItemCount); setStage('MATCH_PACKAGE'); });
  const resetItem = () => { setCandidate(null); setVerification({ status: 'PENDING', confidence: null, reasons: [] }); setBarcode(null); const next = lineIndex + 1; if (receipt && next < receipt.lines.length) { setLineIndex(next); setStage('CAPTURE_ITEM'); } else if (session) { void run(async () => { setSummary(await receivingApi.summary(session.receivingSessionId)); setStage('RECEIPT_SUMMARY'); }); } };

  return <><AppHeader title="Receive Delivery" subtitle="Package intake, identity verification, and barcode allocation"/><main className="mx-auto max-w-md space-y-4 p-4 pb-28">
    <ScreenCard><ReceiveProgress current={stage}/></ScreenCard>
    {error && <ReceiveErrorBanner message={errorText[error] || error} onRetry={() => setError(null)}/>} 
    {receipt && session && !['SCAN_PACKAGE','MATCH_PACKAGE','INSPECT_PACKAGE','OPEN_SESSION'].includes(stage) && <ReceiptSessionBanner receipt={receipt} session={session}/>} 

    {stage === 'SCAN_PACKAGE' && <ScreenCard><div className="relative overflow-hidden rounded-[2rem] border-2 border-dashed border-tcds-gold bg-white p-9 text-center shadow-inner"><div className="absolute left-8 right-8 top-1/2 h-1 -translate-y-1/2 rounded-full bg-tcds-gold/60 scan-pulse"/><ScanLine className="relative mx-auto mb-4 text-tcds-black" size={56}/><p className="relative font-display text-2xl font-black tracking-tight text-tcds-ink">READY TO RECEIVE</p><p className="relative mt-2 text-sm font-semibold text-tcds-muted">Scan tracking, receipt, purchase, or source barcode</p></div>{manual && <input autoFocus value={identifier} onChange={e=>setIdentifier(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void match()} placeholder="Tracking, receipt, or order number" className="tcds-focus mt-4 min-h-14 w-full rounded-2xl border border-tcds-line bg-white px-4 text-base font-bold"/>}<PrimaryButton className="mt-4" disabled={busy || (!identifier && manual)} onClick={() => manual ? void match() : setManual(true)}>{busy?'Matching package…':manual?'Match Package':'Enter Identifier Manually'}</PrimaryButton><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><StatusTile label="Receiving Station" value={bootstrap?.station.stationCode || 'Checking…'}/><StatusTile label="Scanner" value={bootstrap?.scanner.ready?'Ready':'Not ready'} good={bootstrap?.scanner.ready}/><StatusTile label="Network" value={navigator.onLine?'Online':'Offline'} good={navigator.onLine}/><StatusTile label="Offline Queue" value={`${bootstrap?.offlineQueueCount ?? 0} Pending`} good={!bootstrap?.offlineQueueCount}/></div>{bootstrap && !bootstrap.station.ready && <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-900">Receiving station is not ready: {bootstrap.station.reasons.join(', ')}</div>}</ScreenCard>}

    {stage === 'MATCH_PACKAGE' && receipt && <ScreenCard><StageHeading icon={<PackageCheck/>} eyebrow="Package matched" title={receipt.receiptNumber}/><div className="mt-4 space-y-3"><InfoRow label="Source" value={receipt.sourceSystem}/><InfoRow label="Source order" value={receipt.sourceOrderId}/><InfoRow label="Carrier" value={receipt.carrierCode}/><InfoRow label="Tracking" value={receipt.trackingNumber}/><InfoRow label="Expected items" value={String(receipt.expectedItemCount)}/><InfoRow label="Expected packages" value={String(receipt.packageCount)}/></div><PrimaryButton className="mt-5" onClick={()=>setStage('INSPECT_PACKAGE')}>Confirm Physical Package</PrimaryButton><button onClick={()=>{setReceipt(null);setIdentifier('');setStage('SCAN_PACKAGE')}} className="tcds-focus mt-3 min-h-12 w-full rounded-2xl border border-tcds-line bg-white font-black text-tcds-ink">Not the Correct Receipt</button></ScreenCard>}

    {stage === 'INSPECT_PACKAGE' && receipt && <ScreenCard><StageHeading icon={<ShieldCheck/>} eyebrow="Before opening" title="Inspect Unopened Package"/><label className="mt-4 block text-sm font-black text-tcds-ink">Package condition<select value={packageCondition} onChange={e=>setPackageCondition(e.target.value as PackageCondition)} className="tcds-focus mt-2 min-h-14 w-full rounded-2xl border border-tcds-line bg-white px-4 text-base font-bold">{['INTACT','CRUSHED','PUNCTURED','WET','OPENED','RESEALED','TAMPERED','OTHER'].map(v=><option key={v}>{v}</option>)}</select></label><ToggleRow label="Seal intact" checked={sealIntact} onChange={setSealIntact}/><ToggleRow label="Visible damage" checked={visibleDamage} onChange={setVisibleDamage}/><ToggleRow label="Carrier label clear" checked={carrierLabelClear} onChange={setCarrierLabelClear}/>{requiresEvidence && <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3 text-sm font-bold text-amber-900"><AlertTriangle className="shrink-0"/>Package evidence is mandatory before continuing.</div><button onClick={()=>setEvidenceAssetIds(ids=>[...ids,crypto.randomUUID()])} className="tcds-focus mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-amber-200 bg-white font-black text-amber-900"><Camera size={18}/>Capture Evidence Photo ({evidenceAssetIds.length})</button></div>}<PrimaryButton className="mt-5" disabled={busy || (requiresEvidence && evidenceAssetIds.length<3)} onClick={()=>void run(async()=>{const r=await receivingApi.saveInspection(receipt.receiptId,{packageCondition,sealIntact,visibleDamage,carrierLabelClear,evidenceAssetIds}); if(!r.evidenceSatisfied) throw new Error('EVIDENCE_REQUIRED'); setInboundPackageId(r.inboundPackageId);setStage('OPEN_SESSION')})}>{busy?'Saving inspection…':'Save Inspection'}</PrimaryButton></ScreenCard>}

    {stage === 'OPEN_SESSION' && receipt && inboundPackageId && <ScreenCard><StageHeading icon={<ClipboardCheck/>} eyebrow="Receiving control" title="Open Receiving Session"/><p className="mt-3 text-sm font-semibold text-tcds-muted">This creates the authoritative operator, device, station, receipt, and package session used for every item in this delivery.</p><PrimaryButton className="mt-5" disabled={busy} onClick={()=>void run(async()=>{const s=await receivingApi.openSession(receipt.receiptId,inboundPackageId);setSession(s);setStage('COUNT_CONTENTS')})}>{busy?'Opening session…':'Open Session & Continue'}</PrimaryButton></ScreenCard>}

    {stage === 'COUNT_CONTENTS' && receipt && session && <ScreenCard><StageHeading icon={<Box/>} eyebrow="After opening" title="Count Package Contents"/><div className="mt-4 grid grid-cols-2 gap-3"><StatusTile label="Expected" value={String(receipt.expectedItemCount)}/><label className="rounded-2xl bg-tcds-surface p-3 text-sm font-semibold text-tcds-muted">Physical count<input min={0} type="number" value={actualCount} onChange={e=>setActualCount(Math.max(0,Number(e.target.value)))} className="tcds-focus mt-2 min-h-12 w-full rounded-xl border border-tcds-line bg-white px-3 text-base font-black text-tcds-ink"/></label></div>{actualCount!==receipt.expectedItemCount&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">A structured count exception will be created. Blocking discrepancies must be resolved before receipt completion.</div>}<PrimaryButton className="mt-5" disabled={busy||actualCount===0} onClick={()=>void run(async()=>{await receivingApi.reconcileContents(session.receivingSessionId,actualCount);setStage('CAPTURE_ITEM')})}>{busy?'Reconciling contents…':'Confirm Count & Receive Items'}</PrimaryButton></ScreenCard>}

    {stage === 'CAPTURE_ITEM' && receipt && session && <ScreenCard><StageHeading icon={<ScanLine/>} eyebrow={`Item ${lineIndex+1} of ${receipt.lines.length}`} title={item.expectedTitle||'Capture Item Identity'}/><div className="mt-4 space-y-3"><Field label="UPC / EAN / GTIN" value={item.upc} onChange={v=>setItem({...item,upc:v})}/><Field label="Manufacturer part number" value={item.manufacturerPartNumber} onChange={v=>setItem({...item,manufacturerPartNumber:v})}/><Field label={`Serial number${receipt.lines[lineIndex]?.requiresSerial?' (required)':''}`} value={item.serialNumber} onChange={v=>setItem({...item,serialNumber:v})}/><label className="block text-sm font-black text-tcds-ink">Condition<select value={item.condition} onChange={e=>setItem({...item,condition:e.target.value as IntakeItemDraft['condition']})} className="tcds-focus mt-2 min-h-14 w-full rounded-2xl border border-tcds-line bg-white px-4 text-base font-bold">{['UNKNOWN','NEW','LIKE_NEW','GOOD','FAIR','DAMAGED'].map(v=><option key={v}>{v}</option>)}</select></label><ToggleRow label="I verified the physical item and submitted information are accurate" checked={item.employeeConfirmed} onChange={v=>setItem({...item,employeeConfirmed:v})}/></div><PrimaryButton className="mt-5" disabled={!canSubmit||busy} onClick={()=>setStage('EMPLOYEE_SUBMIT')}>Review Required Data</PrimaryButton></ScreenCard>}

    {stage === 'EMPLOYEE_SUBMIT' && session && <ScreenCard><StageHeading icon={<ClipboardCheck/>} eyebrow="Employee verification gate" title="Submit Receiving Data"/><div className="mt-4 space-y-2"><InfoRow label="Expected item" value={item.expectedTitle}/><InfoRow label="UPC / GTIN" value={item.upc}/><InfoRow label="MPN" value={item.manufacturerPartNumber||'Not provided'}/><InfoRow label="Serial" value={item.serialNumber||'Not required'}/><InfoRow label="Condition" value={item.condition}/></div><PrimaryButton className="mt-5" disabled={busy} onClick={()=>void run(async()=>{const c=await receivingApi.createCandidate(session.receivingSessionId,item);setCandidate(c);setStage('SERVER_VALIDATE')})}>{busy?'Submitting…':'Submit Verified Receiving Data'}</PrimaryButton></ScreenCard>}

    {stage === 'SERVER_VALIDATE' && candidate && <ProcessingCard icon={<ShieldCheck/>} title="Server validating completeness" message="Required fields, identifier format, duplicate risk, receipt consistency, employee authorization, device trust, station authorization, evidence, and idempotency are checked." button={busy?'Validating…':'Run Server Validation'} disabled={busy} onClick={()=>void run(async()=>{const r=await receivingApi.validateCandidate(candidate.intakeCandidateId);if(!r.passed)throw new Error(r.errors.join('; '));setStage('INTELLIGENCE_VERIFY');setVerification({status:'PROCESSING',confidence:null,reasons:[]});await receivingApi.verifyCandidate(candidate.intakeCandidateId)})}/>} 
    {stage === 'INTELLIGENCE_VERIFY' && <ProcessingCard icon={<Sparkles/>} title="Intelligence engine verifying product identity" message="Expected purchase data, UPC/GTIN, manufacturer, model, serial uniqueness, evidence, substitution risk, and confidence are evaluated. You may leave this screen; the server owns the verification state."/>}

    {stage === 'VERIFIED_FOR_INTAKE' && candidate && <ScreenCard><StageHeading icon={<CheckCircle2/>} eyebrow="Verification accepted" title="VERIFIED_FOR_INTAKE"/><div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-black text-emerald-900">Identity confidence: {verification.confidence ?? 'Verified'}{verification.confidence!==null?'%':''}</p><ul className="mt-2 space-y-1 text-sm font-semibold text-emerald-900">{verification.reasons.map(r=><li key={r}>✓ {r}</li>)}</ul></div><p className="mt-4 text-sm font-semibold text-tcds-muted">The server may now atomically create the item, identifiers, permanent TCDS barcode, audit records, domain event, and outbox event. No label is printed at receiving.</p><PrimaryButton className="mt-5" disabled={busy} onClick={()=>void run(async()=>{setBarcode(await receivingApi.allocateBarcode(candidate.intakeCandidateId));setStage('BARCODE_ALLOCATED')})}>{busy?'Committing barcode…':'Allocate & Persist TCDS Barcode'}</PrimaryButton></ScreenCard>}

    {stage === 'REVIEW_REQUIRED' && <ScreenCard><StageHeading icon={<AlertTriangle/>} eyebrow="Identity review" title="Supervisor Review Required"/><p className="mt-4 text-sm font-semibold text-tcds-muted">No active TCDS barcode has been issued. The item remains on receiving hold while the review task is resolved.</p><InfoRow label="Confidence" value={verification.confidence===null?'Pending':`${verification.confidence}%`}/><InfoRow label="Review task" value={verification.reviewTaskId||'Created by server'}/><PrimaryButton className="mt-5" onClick={resetItem}>Continue to Next Item</PrimaryButton></ScreenCard>}
    {stage === 'REJECTED' && <ScreenCard><StageHeading icon={<AlertTriangle/>} eyebrow="Verification rejected" title="Barcode Issuance Blocked"/><p className="mt-4 text-sm font-semibold text-tcds-muted">The item does not sufficiently match the expected purchase. It remains in receiving hold and requires supervisor resolution.</p><PrimaryButton className="mt-5" onClick={resetItem}>Continue to Next Item</PrimaryButton></ScreenCard>}

    {stage === 'BARCODE_ALLOCATED' && barcode && <ScreenCard><StageHeading icon={<Barcode/>} eyebrow="PostgreSQL committed" title="TCDS Barcode Allocated"/><div className="mt-4 rounded-[1.6rem] bg-tcds-black p-5 text-center text-white"><Barcode className="mx-auto text-tcds-gold" size={44}/><p className="mt-3 font-mono text-lg font-black tracking-wider">{barcode.value}</p><p className="mt-2 text-xs font-black uppercase tracking-[0.18em] text-tcds-gold">{barcode.status}</p></div><div className="mt-4 space-y-2"><InfoRow label="Print status" value="Pending repackaging"/><InfoRow label="Label printed now" value="No"/><InfoRow label="Committed" value={new Date(barcode.committedAt).toLocaleString()}/></div><PrimaryButton className="mt-5" onClick={()=>setStage('HANDOFF')}>Continue to Photos</PrimaryButton></ScreenCard>}

    {stage === 'HANDOFF' && session && barcode && <ScreenCard><StageHeading icon={<PackageCheck/>} eyebrow="Receiving handoff complete" title="Ready for Photos"/><div className="mt-4 space-y-2"><InfoRow label="Receiving status" value="VERIFIED_FOR_INTAKE"/><InfoRow label="Barcode" value={barcode.value}/><InfoRow label="Barcode print" value="Deferred to repackaging"/><InfoRow label="Next workflow" value="Photos → Detailed Verify → Storage"/></div><PrimaryButton className="mt-5" onClick={()=>navigate('/photos',{state:{receivingSessionId:session.receivingSessionId,itemId:barcode.itemId,barcodeId:barcode.barcodeId,returnTo:'/receive'}})}>Open Photo Workflow</PrimaryButton><button onClick={resetItem} className="tcds-focus mt-3 min-h-12 w-full rounded-2xl border border-tcds-line bg-white font-black text-tcds-ink">Process Next Item</button></ScreenCard>}

    {stage === 'RECEIPT_SUMMARY' && session && summary && <ScreenCard><StageHeading icon={<PackageCheck/>} eyebrow="Receiving session summary" title="Review Before Completion"/><div className="mt-4 grid grid-cols-2 gap-3"><StatusTile label="Expected" value={String(summary.expectedItems)}/><StatusTile label="Processed" value={String(summary.processedItems)}/><StatusTile label="Verified" value={String(summary.verifiedItems)} good/><StatusTile label="Review" value={String(summary.reviewItems)}/><StatusTile label="Rejected" value={String(summary.rejectedItems)}/><StatusTile label="Blocking exceptions" value={String(summary.blockingExceptions)}/></div><PrimaryButton className="mt-5" disabled={!summary.canComplete||busy} onClick={()=>void run(async()=>{await receivingApi.completeSession(session.receivingSessionId);navigate('/dashboard',{replace:true})})}>{busy?'Completing receipt…':'Complete Receiving Session'}</PrimaryButton>{!summary.canComplete&&<p className="mt-3 text-sm font-bold text-tcds-red">Receipt completion is blocked until all required items and exceptions are resolved.</p>}</ScreenCard>}

    <ScreenCard><h2 className="font-display text-lg font-black text-tcds-ink">Locked Receiving Rule</h2><p className="mt-2 text-sm font-semibold leading-6 text-tcds-muted">The permanent TCDS barcode is allocated only after employee submission, server validation, and intelligence verification. It is persisted during receiving and printed later during repackaging or relabeling.</p></ScreenCard>
  </main></>;
}

function StageHeading({icon,eyebrow,title}:{icon:JSX.Element;eyebrow:string;title:string}){return <div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-tcds-gold/15 text-tcds-goldDeep">{icon}</div><div><p className="text-xs font-black uppercase tracking-[0.2em] text-tcds-goldDeep">{eyebrow}</p><h2 className="mt-1 font-display text-xl font-black text-tcds-ink">{title}</h2></div></div>}
function StatusTile({label,value,good=false}:{label:string;value:string;good?:boolean}){return <div className="rounded-2xl bg-tcds-surface p-3"><p className="text-sm font-semibold text-tcds-muted">{label}</p><p className={`mt-1 font-black ${good?'text-tcds-green':'text-tcds-ink'}`}>{value}</p></div>}
function InfoRow({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-4 rounded-2xl bg-tcds-surface p-3"><span className="text-sm font-semibold text-tcds-muted">{label}</span><span className="text-right text-sm font-black text-tcds-ink">{value}</span></div>}
function ToggleRow({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="mt-3 flex min-h-14 items-center justify-between rounded-2xl border border-tcds-line bg-tcds-surface px-4"><span className="pr-3 text-sm font-black text-tcds-ink">{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-6 w-6 accent-[#c99a35]"/></label>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-black text-tcds-ink">{label}<input value={value} onChange={e=>onChange(e.target.value)} autoCapitalize="characters" className="tcds-focus mt-2 min-h-14 w-full rounded-2xl border border-tcds-line bg-white px-4 text-base font-bold"/></label>}
function ProcessingCard({icon,title,message,button,onClick,disabled=false}:{icon:JSX.Element;title:string;message:string;button?:string;onClick?:()=>void;disabled?:boolean}){return <ScreenCard><StageHeading icon={icon} eyebrow="Authoritative processing gate" title={title}/><div className="mt-5 rounded-2xl border border-tcds-gold/20 bg-tcds-gold/5 p-4"><div className="mb-3 h-2 overflow-hidden rounded-full bg-tcds-line"><div className="h-full w-2/3 animate-pulse rounded-full bg-tcds-gold"/></div><p className="text-sm font-semibold leading-6 text-tcds-muted">{message}</p></div>{button&&onClick&&<PrimaryButton className="mt-5" disabled={disabled} onClick={onClick}>{button}</PrimaryButton>}</ScreenCard>}
