export const DOMAIN11B_AGGREGATOR = "DOMAIN11B_AGGREGATOR" as const;
export const DOMAIN11B_PROBE = "DOMAIN11B_PROBE" as const;
export const DOMAIN11B_PUSH = "DOMAIN11B_PUSH" as const;
export const DOMAIN11B_CERTIFIED_OVERRIDE = "DOMAIN11B_CERTIFIED_OVERRIDE" as const;

export const HEALTH_STATES = [
  "PROCESS_ALIVE","DEPENDENCY_REACHABLE","DEPENDENCY_HEALTHY","FUNCTIONAL","DEGRADED","UNAVAILABLE","UNKNOWN",
] as const;
export const HEALTH_OUTCOMES = ["SUCCESS","FAILURE","UNKNOWN"] as const;
export const HEALTH_CHECK_MODES = ["PULL","PUSH","SYNTHETIC"] as const;
