import { randomUUID } from 'node:crypto';
import { Router, type Request, type RequestHandler, type Response } from 'express';
import type { AccountabilityPrincipal, AuditEventInput, Domain11MutationInput, ExternalReferenceInput, LineageEdgeInput, EventLinkInput } from '../models/accountabilityTypes';
import type { AccountabilityRepository } from '../repositories/accountabilityRepository';
import type { AccountabilityService } from '../services/accountabilityService';
import { boundedInt, optionalUuid, requireDate, requireDomain, requireEnum, requireObject, requireSha, requireString, requireUuid } from '../validators/accountabilityValidators';
function principal(res:Response){return res.locals.accountabilityPrincipal as AccountabilityPrincipal;}
function rid(req:Request){const r=req as Request&{__requestId?:string};if(r.__requestId)return r.__requestId;const v=req.headers['x-request-id'];if(v===undefined){r.__requestId=randomUUID();return r.__requestId;}if(typeof v!=='string')throw Object.assign(new Error('invalid_request_id'),{statusCode:400});r.__requestId=requireUuid(v,'request_id');return r.__requestId;}
function cid(req:Request){const r=req as Request&{__correlationId?:string};if(r.__correlationId)return r.__correlationId;const v=req.headers['x-correlation-id'];if(v===undefined){r.__correlationId=randomUUID();return r.__correlationId;}if(typeof v!=='string')throw Object.assign(new Error('invalid_correlation_id'),{statusCode:400});r.__correlationId=requireUuid(v,'correlation_id');return r.__correlationId;}
export interface AccountabilityRouteAuth{read:RequestHandler;mutationWrite:RequestHandler;auditWrite:RequestHandler;lineageWrite:RequestHandler;externalReport:RequestHandler;admin:RequestHandler;}
export function createAccountabilityRoutes(input:{auth:AccountabilityRouteAuth;service:AccountabilityService;repo:AccountabilityRepository}){const r=Router();
 r.post('/governance/mutations/domain11',input.auth.mutationWrite,async(req,res,next)=>{try{const b=req.body as Record<string,unknown>;const x:Domain11MutationInput={sourceSchema:requireString(b.sourceSchema,'source_schema'),sourceTable:requireString(b.sourceTable,'source_table'),sourceEntityId:requireString(b.sourceEntityId,'source_entity_id'),mutationKind:requireEnum(b.mutationKind,'mutation_kind',['INSERT','UPDATE','DELETE','STATE_TRANSITION'] as const),beforeState:b.beforeState===null?null:requireObject(b.beforeState,'before_state'),afterState:b.afterState===null?null:requireObject(b.afterState,'after_state'),actorType:'USER',requestId:rid(req),correlationId:cid(req),policyVersionId:optionalUuid(b.policyVersionId,'policy_version_id'),occurredAt:requireDate(b.occurredAt??new Date().toISOString(),'occurred_at'),idempotencyKey:requireString(b.idempotencyKey,'idempotency_key')};res.status(201).json({mutationLedgerId:await input.service.domain11Mutation(principal(res),x)});}catch(e){next(e);}});
 r.post('/governance/mutations/external-reference',input.auth.externalReport,async(req,res,next)=>{try{const b=req.body as Record<string,unknown>;const x:ExternalReferenceInput={domainCode:requireDomain(b.domainCode),sourceSchema:requireString(b.sourceSchema,'source_schema'),sourceTable:requireString(b.sourceTable,'source_table'),sourceEntityId:requireString(b.sourceEntityId,'source_entity_id'),externalLedgerId:requireString(b.externalLedgerId,'external_ledger_id'),externalRecordSha256:requireSha(b.externalRecordSha256,'external_record_sha256'),actorType:'USER',requestId:rid(req),correlationId:cid(req),occurredAt:requireDate(b.occurredAt??new Date().toISOString(),'occurred_at'),idempotencyKey:requireString(b.idempotencyKey,'idempotency_key')};res.status(202).json({mutationLedgerId:await input.service.externalReference(principal(res),x)});}catch(e){next(e);}});
 r.post('/governance/audit/events',input.auth.auditWrite,async(req,res,next)=>{try{const b=req.body as Record<string,unknown>;const x:AuditEventInput={eventType:requireString(b.eventType,'event_type'),severity:requireEnum(b.severity,'severity',['DEBUG','INFO','NOTICE','WARNING','ERROR','CRITICAL'] as const),actorType:'USER',targetDomainCode:b.targetDomainCode?requireDomain(b.targetDomainCode):undefined,targetReference:typeof b.targetReference==='string'?b.targetReference:undefined,sourceComponentId:undefined,action:requireString(b.action,'action'),outcome:requireEnum(b.outcome,'outcome',['SUCCESS','DENIED','FAILED','PARTIAL','OBSERVED'] as const),requestId:rid(req),correlationId:cid(req),remoteAddressHash:undefined,details:requireObject(b.details,'details'),occurredAt:requireDate(b.occurredAt??new Date().toISOString(),'occurred_at'),idempotencyKey:requireString(b.idempotencyKey,'idempotency_key')};res.status(201).json({auditEventId:await input.service.audit(principal(res),x)});}catch(e){next(e);}});
 r.post('/governance/lineage/edges',input.auth.lineageWrite,async(req,res,next)=>{try{const b=req.body as Record<string,unknown>;const s=requireObject(b.source,'source'),t=requireObject(b.target,'target');const x:LineageEdgeInput={source:{domainCode:requireDomain(s.domainCode),entityType:requireString(s.entityType,'source_entity_type'),entityId:requireString(s.entityId,'source_entity_id'),authoritativeReference:typeof s.authoritativeReference==='string'?s.authoritativeReference:undefined},relationshipType:requireString(b.relationshipType,'relationship_type'),target:{domainCode:requireDomain(t.domainCode),entityType:requireString(t.entityType,'target_entity_type'),entityId:requireString(t.entityId,'target_entity_id'),authoritativeReference:typeof t.authoritativeReference==='string'?t.authoritativeReference:undefined},correlationId:cid(req),causationId:optionalUuid(b.causationId,'causation_id'),requestId:rid(req),occurredAt:requireDate(b.occurredAt??new Date().toISOString(),'occurred_at'),sourceComponentId:undefined,referenceMetadata:requireObject(b.referenceMetadata,'reference_metadata'),idempotencyKey:requireString(b.idempotencyKey,'idempotency_key')};res.status(201).json({lineageEdgeId:await input.service.edge(principal(res),x)});}catch(e){next(e);}});
 r.post('/governance/lineage/event-links',input.auth.lineageWrite,async(req,res,next)=>{try{const b=req.body as Record<string,unknown>;const x:EventLinkInput={mutationLedgerId:optionalUuid(b.mutationLedgerId,'mutation_ledger_id'),auditEventId:optionalUuid(b.auditEventId,'audit_event_id'),lineageEdgeId:optionalUuid(b.lineageEdgeId,'lineage_edge_id'),domainEventId:requireUuid(b.domainEventId,'domain_event_id'),outboxEventId:optionalUuid(b.outboxEventId,'outbox_event_id'),correlationId:cid(req),causationId:optionalUuid(b.causationId,'causation_id'),idempotencyKey:requireString(b.idempotencyKey,'idempotency_key')};res.status(201).json({eventLineageLinkId:await input.service.eventLink(principal(res),x)});}catch(e){next(e);}});
 r.post('/governance/lineage/source-authorities/:bindingId/revoke',input.auth.admin,async(req,res,next)=>{try{const b=req.body as Record<string,unknown>;const eventId=await input.service.revokeSourceAuthority(principal(res),requireUuid(req.params.bindingId,'binding_id'),requireString(b.reason,'reason'));res.status(200).json({authorityBindingEventId:eventId,status:'REVOKED'});}catch(e){next(e);}});
 r.get('/governance/lineage/entity/:domain/:type/:id',input.auth.read,async(req,res,next)=>{try{const direction=typeof req.query.direction==='string'?req.query.direction.toUpperCase():'BOTH';if(!['IN','OUT','BOTH'].includes(direction))throw Object.assign(new Error('invalid_direction'),{statusCode:400});const edges=await input.repo.walk(requireDomain(req.params.domain),requireString(req.params.type,'type'),requireString(req.params.id,'id'),direction,boundedInt(req.query.depth,'depth',1,12,6),boundedInt(req.query.limit,'limit',1,2000,500));await input.service.accessAudit(principal(res),'VIEW_LINEAGE_ENTITY',`${req.params.domain}:${req.params.type}:${req.params.id}`,rid(req),cid(req));res.json({edges});}catch(e){next(e);}});
 r.get('/governance/lineage/correlation/:id',input.auth.read,async(req,res,next)=>{try{const timeline=await input.repo.correlation(requireUuid(req.params.id,'correlation_id'),boundedInt(req.query.limit,'limit',1,2000,500));await input.service.accessAudit(principal(res),'VIEW_CORRELATION',String(req.params.id??''),rid(req),cid(req));res.json({timeline});}catch(e){next(e);}});
 r.get('/governance/audit/timeline',input.auth.read,async(req,res,next)=>{try{const timeline=await input.repo.timeline(typeof req.query.domain==='string'?requireDomain(req.query.domain):undefined,typeof req.query.entityId==='string'?req.query.entityId:undefined,boundedInt(req.query.limit,'limit',1,2000,500));await input.service.accessAudit(principal(res),'VIEW_AUDIT_TIMELINE',String(req.query.entityId??req.query.domain??'all'),rid(req),cid(req));res.json({timeline});}catch(e){next(e);}});
 r.get('/governance/lineage/transactions/:id',input.auth.read,async(req,res,next)=>{try{if(!/^\d+$/.test(String(req.params.id??'')))throw Object.assign(new Error('invalid_transaction_id'),{statusCode:400});const evidence=await input.repo.transaction(String(req.params.id),boundedInt(req.query.limit,'limit',1,2000,500));await input.service.accessAudit(principal(res),'VIEW_TRANSACTION',String(req.params.id),rid(req),cid(req));res.json({evidence});}catch(e){next(e);}});
 r.get('/governance/lineage/requests/:id',input.auth.read,async(req,res,next)=>{try{const evidence=await input.repo.request(requireUuid(req.params.id,'request_id'),boundedInt(req.query.limit,'limit',1,2000,500));await input.service.accessAudit(principal(res),'VIEW_REQUEST',String(req.params.id??''),rid(req),cid(req));res.json({evidence});}catch(e){next(e);}});
 r.get('/governance/lineage/policies/:versionId',input.auth.read,async(req,res,next)=>{try{const evidence=await input.repo.policy(requireUuid(req.params.versionId,'policy_version_id'),boundedInt(req.query.limit,'limit',1,2000,500));await input.service.accessAudit(principal(res),'VIEW_POLICY_LINEAGE',String(req.params.versionId??''),rid(req),cid(req));res.json({evidence});}catch(e){next(e);}});
 r.get('/governance/lineage/external/:domain/:entityId',input.auth.read,async(req,res,next)=>{try{const references=await input.repo.external(requireDomain(req.params.domain),requireString(req.params.entityId,'entity_id'),boundedInt(req.query.limit,'limit',1,2000,500));await input.service.accessAudit(principal(res),'VIEW_EXTERNAL_REFERENCE',`${req.params.domain}:${req.params.entityId}`,rid(req),cid(req));res.json({references});}catch(e){next(e);}});
 r.get('/governance/lineage/chains/:stream/verify',input.auth.read,async(req,res,next)=>{try{const result=await input.repo.verify(requireDomain(req.params.stream));await input.service.accessAudit(principal(res),'VERIFY_CHAIN',String(req.params.stream??''),rid(req),cid(req));res.json(result);}catch(e){next(e);}});return r;}
