import{Router,type RequestHandler}from'express';
import type{ReleaseCertificationService}from'../services/releaseCertificationService';
import type{ReleasePrincipal}from'../models/releaseCertificationTypes';
import{uuid,sha256,nonEmpty,positiveInt,isoDate,manifest,oneOf}from'../validators/releaseCertificationValidators';
export function createReleaseCertificationRoutes(x:{service:ReleaseCertificationService;read:RequestHandler;admin:RequestHandler;certify:RequestHandler;replay:RequestHandler;deploy:RequestHandler}){
 const r=Router(),p=(s:any)=>s.locals.releasePrincipal as ReleasePrincipal;
 r.post('/governance/release/admin/sync-policy',x.admin,async(_q,s,n)=>{try{s.json(await x.service.syncPolicy(p(s)))}catch(e){n(e)}});
 r.get('/governance/release/:id',x.read,async(q,s,n)=>{try{const z=await x.service.summary(p(s),uuid(q.params.id));if(!z){s.status(404).json({error:'RELEASE_NOT_FOUND'});return}s.json(z)}catch(e){n(e)}});
 r.post('/governance/release',x.admin,async(q,s,n)=>{try{s.status(201).json(await x.service.register(p(s),{manifest:manifest(q.body?.manifest),requestId:uuid(q.body?.requestId),correlationId:uuid(q.body?.correlationId),idempotencyKey:nonEmpty(q.body?.idempotencyKey,'IDEMPOTENCY_KEY')}))}catch(e){n(e)}});
 r.post('/governance/release/:id/seal',x.admin,async(q,s,n)=>{try{s.json(await x.service.seal(p(s),uuid(q.params.id)))}catch(e){n(e)}});
 r.post('/governance/release/:id/certifications',x.certify,async(q,s,n)=>{try{s.status(201).json(await x.service.start(p(s),{releaseCandidateId:uuid(q.params.id),environment:oneOf(q.body?.environment,'ENVIRONMENT',['DEV','TEST','STAGING','PRODUCTION','DISASTER_RECOVERY'] as const),phase:oneOf(q.body?.phase,'PHASE',['PRE_DEPLOYMENT','CANARY','POST_DEPLOYMENT','ROLLBACK'] as const),requestId:uuid(q.body?.requestId),correlationId:uuid(q.body?.correlationId)}))}catch(e){n(e)}});
 r.post('/governance/release/gates/evidence',x.certify,async(q,s,n)=>{try{s.status(201).json(await x.service.gate(p(s),{certificationRunId:uuid(q.body?.certificationRunId),gateCode:nonEmpty(q.body?.gateCode,'GATE_CODE'),gateVersion:positiveInt(q.body?.gateVersion,'GATE_VERSION'),result:oneOf(q.body?.result,'RESULT',['PASS','PASS_WITH_RESTRICTIONS','FAIL','BLOCKED','NOT_APPLICABLE'] as const),evidenceReference:nonEmpty(q.body?.evidenceReference,'EVIDENCE_REFERENCE'),evidencePayload:q.body?.evidencePayload??{},startedAt:isoDate(q.body?.startedAt,'STARTED_AT'),completedAt:isoDate(q.body?.completedAt,'COMPLETED_AT'),toolRuntime:q.body?.toolRuntime??{},requestId:uuid(q.body?.requestId),correlationId:uuid(q.body?.correlationId)}))}catch(e){n(e)}});
 r.post('/governance/release/certifications/:id/finalize',x.certify,async(q,s,n)=>{try{s.json(await x.service.finalize(p(s),uuid(q.params.id)))}catch(e){n(e)}});
 r.post('/governance/release/rollback/certify',x.certify,async(q,s,n)=>{try{s.status(201).json(await x.service.certifyRollback(p(s),{certificationRunId:uuid(q.body?.certificationRunId),environment:oneOf(q.body?.environment,'ENVIRONMENT',['TEST','STAGING','DISASTER_RECOVERY'] as const),rollbackManifestSha256:sha256(q.body?.rollbackManifestSha256,'ROLLBACK_MANIFEST_SHA'),executionEvidence:q.body?.executionEvidence??{},requestId:uuid(q.body?.requestId),correlationId:uuid(q.body?.correlationId)}))}catch(e){n(e)}});
 r.post('/governance/release/deployment/verify',x.deploy,async(q,s,n)=>{try{s.status(201).json(await x.service.verifyDeployment(p(s),{releaseCandidateId:uuid(q.body?.releaseCandidateId),certificationRunId:uuid(q.body?.certificationRunId),environment:oneOf(q.body?.environment,'ENVIRONMENT',['STAGING','PRODUCTION','DISASTER_RECOVERY'] as const),phase:oneOf(q.body?.phase,'PHASE',['CANARY','POST_DEPLOYMENT'] as const),deployedArtifactManifestSha256:sha256(q.body?.deployedArtifactManifestSha256,'ARTIFACT_SHA'),deployedMigrationManifestSha256:sha256(q.body?.deployedMigrationManifestSha256,'MIGRATION_SHA'),readinessComponentId:uuid(q.body?.readinessComponentId),verificationPayload:q.body?.verificationPayload??{},requestId:uuid(q.body?.requestId),correlationId:uuid(q.body?.correlationId)}))}catch(e){n(e)}});
 r.post('/governance/replay',x.replay,async(q,s,n)=>{try{s.status(201).json(await x.service.beginReplay(p(s),{certificationRunId:uuid(q.body?.certificationRunId),replayScenarioId:uuid(q.body?.replayScenarioId),requestId:uuid(q.body?.requestId),correlationId:uuid(q.body?.correlationId)}))}catch(e){n(e)}});
 r.post('/governance/replay/:id/complete',x.replay,async(q,s,n)=>{try{s.status(201).json(await x.service.completeReplay(p(s),{replayRunId:uuid(q.params.id),actualResult:q.body?.actualResult??{},difference:q.body?.difference??{}}))}catch(e){n(e)}});
 return r;
}