BEGIN;
CREATE TEMP TABLE ups_preflight_results(test_group text,test_name text,test_status text CHECK(test_status IN('PASS','WARN','FAIL')),severity text CHECK(severity IN('LOW','MEDIUM','HIGH','CRITICAL')),message text,created_at timestamptz DEFAULT now()) ON COMMIT PRESERVE ROWS;
WITH expected(table_name) AS (VALUES ('ups_oauth_token_events'),('ups_api_error_events'),('ups_address_validation_events'),('ups_rate_quote_events'),('ups_shipment_label_events'),('ups_label_recovery_events'),('ups_tracking_snapshots'),('ups_tracking_event_details'),('ups_tracking_subscription_events'),('ups_tracking_webhook_events'),('ups_pickup_events'),('ups_claim_events'),('ups_billing_adjustment_events'),('ups_lane_learning_metrics'),('ups_decision_events'))
INSERT INTO ups_preflight_results SELECT 'TABLE','required:'||e.table_name,CASE WHEN t.table_name IS NULL THEN 'FAIL' ELSE 'PASS' END,'CRITICAL',CASE WHEN t.table_name IS NULL THEN 'Missing UPS table.' ELSE 'Table exists.' END,now() FROM expected e LEFT JOIN information_schema.tables t ON t.table_schema='arb' AND t.table_name=e.table_name;
WITH expected(view_name) AS (VALUES ('v_ups_oauth_latest'),('v_ups_address_validation_latest'),('v_ups_rate_quote_latest'),('v_ups_tracking_latest'),('v_ups_profit_protection_dashboard'),('v_ups_learning_dashboard'))
INSERT INTO ups_preflight_results SELECT 'VIEW','required:'||e.view_name,CASE WHEN v.table_name IS NULL THEN 'FAIL' ELSE 'PASS' END,'HIGH',CASE WHEN v.table_name IS NULL THEN 'Missing UPS view.' ELSE 'View exists.' END,now() FROM expected e LEFT JOIN information_schema.views v ON v.table_schema='arb' AND v.table_name=e.view_name;
WITH expected(function_name) AS (VALUES ('ups_error_severity'),('ups_delivery_exception_code'),('ups_score_rate_option'))
INSERT INTO ups_preflight_results SELECT 'FUNCTION','required:'||e.function_name,CASE WHEN p.proname IS NULL THEN 'FAIL' ELSE 'PASS' END,'HIGH',CASE WHEN p.proname IS NULL THEN 'Missing UPS function.' ELSE 'Function exists.' END,now() FROM expected e LEFT JOIN pg_proc p ON p.proname=e.function_name LEFT JOIN pg_namespace n ON n.oid=p.pronamespace AND n.nspname='arb' WHERE n.nspname='arb' OR p.proname IS NULL;
INSERT INTO ups_preflight_results SELECT 'SEED','process_registry_ups_count',CASE WHEN count(*)>=22 THEN 'PASS' ELSE 'FAIL' END,'CRITICAL','UPS process seed count='||count(*)::text,now() FROM arb.process_registry WHERE process_name LIKE 'domain3.shipping.ups.%';
DO $$ DECLARE r record; BEGIN FOR r IN SELECT table_name FROM information_schema.views WHERE table_schema='arb' AND table_name LIKE 'v_ups_%' LOOP BEGIN EXECUTE format('SELECT * FROM arb.%I LIMIT 0',r.table_name); INSERT INTO ups_preflight_results VALUES('VIEW_COMPILE','compile:'||r.table_name,'PASS','HIGH','View compiles.',now()); EXCEPTION WHEN OTHERS THEN INSERT INTO ups_preflight_results VALUES('VIEW_COMPILE','compile:'||r.table_name,'FAIL','HIGH',SQLERRM,now()); END; END LOOP; END $$;
SELECT count(*) total_checks,count(*) FILTER(WHERE test_status='PASS') pass_count,count(*) FILTER(WHERE test_status='WARN') warn_count,count(*) FILTER(WHERE test_status='FAIL') fail_count FROM ups_preflight_results;
SELECT * FROM ups_preflight_results WHERE test_status<>'PASS' ORDER BY severity,test_group,test_name;
DO $$ DECLARE fail_count int; BEGIN SELECT count(*) INTO fail_count FROM ups_preflight_results WHERE test_status='FAIL'; IF fail_count>0 THEN RAISE EXCEPTION 'UPS Green Tier 1 preflight failed with % failures',fail_count; END IF; END $$;
COMMIT;
