import { Pool } from "pg";
import { hashJson, hashText } from "../utils/upsUtils";
import { mapUpsAddressValidation, mapUpsRateLikeResponse, mapUpsTrackResponse } from "../mappers/upsMapper";
export class UpsRepository { constructor(private readonly db: Pool) {}
  async recordAddressValidation(args:{input:any;response:any;shipmentId?:number;ebayOrderFk?:number;processRunId?:string}){ const m=mapUpsAddressValidation(args.response); const {rows}=await this.db.query(`INSERT INTO arb.ups_address_validation_events (shipment_id,ebay_order_fk,request_option,valid_address,ambiguous_address,no_candidates,address_classification_code,address_classification_description,candidate_count,input_json,normalized_candidates_json,raw_response_json,request_hash,response_hash,process_run_id) VALUES ($1,$2,3,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12,$13,$14) RETURNING id`,[args.shipmentId??null,args.ebayOrderFk??null,m.valid,m.ambiguous,m.noCandidates,m.classification?.Code??null,m.classification?.Description??null,m.candidates.length,JSON.stringify(args.input??{}),JSON.stringify(m.candidates),JSON.stringify(args.response??{}),hashJson(args.input),hashJson(args.response),args.processRunId??null]); return Number(rows[0].id); }
  async recordRateQuote(args:{quoteType:"RATE"|"TIME_IN_TRANSIT"|"SERVICE_AVAILABILITY"|"SHIPPING_OPTIONS";request:any;response:any;shipmentId?:number;ebayOrderFk?:number;processRunId?:string}){ const options=mapUpsRateLikeResponse(args.response); const cheapest=options.filter((x)=>x.totalChargeUsd!==undefined).sort((a,b)=>Number(a.totalChargeUsd)-Number(b.totalChargeUsd))[0]; const {rows}=await this.db.query(`INSERT INTO arb.ups_rate_quote_events (shipment_id,ebay_order_fk,quote_type,origin_postal_code,origin_country_code,destination_postal_code,destination_country_code,service_code,service_name,weight_lb,length_in,width_in,height_in,item_value_usd,currency_code,total_charge_usd,selected,request_hash,response_hash,request_json,response_json,normalized_options_json,process_run_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,false,$17,$18,$19::jsonb,$20::jsonb,$21::jsonb,$22) RETURNING id`,[args.shipmentId??null,args.ebayOrderFk??null,args.quoteType,args.request?.originPostalCode??null,args.request?.originCountryCode??null,args.request?.destinationPostalCode??null,args.request?.destinationCountryCode??null,cheapest?.serviceCode??args.request?.serviceCode??null,cheapest?.serviceName??args.request?.serviceName??null,args.request?.weight??null,args.request?.length??null,args.request?.width??null,args.request?.height??null,args.request?.itemValue??null,"USD",cheapest?.totalChargeUsd??null,hashJson(args.request),hashJson(args.response),JSON.stringify(args.request??{}),JSON.stringify(args.response??{}),JSON.stringify(options),args.processRunId??null]); return Number(rows[0].id); }
  async recordTracking(args:{trackingNumber:string;response:any;shipmentId?:number;ebayOrderFk?:number;processRunId?:string}){ const m=mapUpsTrackResponse(args.response); const current=m.currentStatus??{}; const {rows}=await this.db.query(`INSERT INTO arb.ups_tracking_snapshots (shipment_id,ebay_order_fk,tracking_number,current_status_code,current_status_description,current_status_type,package_json,raw_response_json,snapshot_hash,process_run_id) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10) RETURNING id`,[args.shipmentId??null,args.ebayOrderFk??null,args.trackingNumber,current?.code??null,current?.description??null,current?.type??null,JSON.stringify(m.package??{}),JSON.stringify(args.response??{}),hashJson(args.response),args.processRunId??null]); return Number(rows[0].id); }
  async recordWebhook(args:{headers:any;payload:any;credential?:string;credentialValid?:boolean}){ const payload=args.payload??{}; const {rows}=await this.db.query(`INSERT INTO arb.ups_tracking_webhook_events (tracking_number,credential_hash,credential_valid,user_agent,activity_status_code,activity_status_description,activity_location_json,raw_payload,payload_hash) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9) ON CONFLICT (tracking_number,payload_hash) DO UPDATE SET processing_status='DUPLICATE' RETURNING id`,[payload.trackingNumber,args.credential?hashText(args.credential):null,args.credentialValid??null,args.headers?.["user-agent"]??args.headers?.["User-Agent"]??null,payload.activityStatus?.code??payload.activityStatus?.statusCode??null,payload.activityStatus?.description??payload.activityStatus?.statusDescription??null,JSON.stringify(payload.activityLocation??{}),JSON.stringify(payload),hashJson(payload)]); return Number(rows[0].id); }
}
